/**
 * pKapp - Banco de preguntas - Neurobiología
 *
 * El contenido de estas preguntas NO pertenece a pKapp ni a Agustín Frusto:
 * se basa en material de estudio de terceros, cuyos derechos pertenecen a sus
 * autores originales. Se reproduce sin fines comerciales y con fines
 * exclusivamente educativos (uso NO comercial).
 * Reclamos de derechos: agustinfrusto@gmail.com
 */
// Estructura: { id, source, exam, topic, materia: 'neuro', question, options, correctIndex, explanation }
// Materia sin parciales. explanation: null hasta generar las explicaciones (Paso 6).
export const QUESTIONS = [
  {
    id: "N-P1-Q1", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "organizacion-sn", materia: 'neuro',
    question: "Respecto a la organización funcional del sistema nervioso, es correcto afirmar que:",
    options: ["El hipotálamo participa en el control fino del movimiento voluntario.", "Las áreas corticales de asociación intervienen en la integración sensoriomotora.", "El sistema sensorial controla directamente los actos motores mediante motoneuronas."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q2", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "membrana-potencial", materia: 'neuro',
    question: "Respecto al potencial de acción en una neurona, es correcto afirmar que:",
    options: ["Se genera independientemente del umbral de despolarización.", "Se propaga a lo largo del axón sin decremento de amplitud.", "No presenta periodos refractarios."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q3", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "sinapsis", materia: 'neuro',
    question: "En dos neuronas comunicadas mediante uniones GAP es correcto afirmar que la transmisión de corriente:",
    options: ["No ocurre si es hiperpolarizante.", "Presenta un retardo sináptico de 50 ms.", "Ocurre a voltajes de membrana subumbrales"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q4", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "Con respecto al sistema sensorial táctil, marque la opción correcta:",
    options: ["Los receptores de Merkel son de adaptación rápida.", "La tercera neurona de la vía se encuentra en el tálamo.", "Los campos receptivos de la espalda son más pequeños que los de las yemas de los dedos."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q5", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "Con respecto a los receptores sensoriales, marque la opción correcta:",
    options: ["Los estímulos más intensos producen un potencial receptor de mayor amplitud.", "La transducción sensorial implica la transformación de energía eléctrica en química.", "La forma del potencial de acción depende de la amplitud de los estímulos mecánicos."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q6", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "Con respecto al fenómeno de adaptación sensorial, marque la opción correcta:",
    options: ["Los receptores de adaptación rápida responden continuamente durante un estímulo constante y prolongado.", "Los receptores de adaptación rápida responden frente a modificaciones en la intensidad del estímulo.", "Los receptores de adaptación lenta se inactivan mientras el estímulo es constante."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q7", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "control-motor", materia: 'neuro',
    question: "Respecto a los movimientos voluntarios, indique la opción correcta:",
    options: ["Su ejecución depende exclusivamente de reflejos medulares.", "Mejoran su precisión con la práctica y la repetición.", "Su inicio es independiente del control cortical."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q8", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "control-motor", materia: 'neuro',
    question: "En relación con las vías centrales y las cortezas motoras que modulan los actos motores, es correcto afirmar que:",
    options: ["La corteza motora primaria carece de somatotopia.", "Las cortezas motoras reciben aferencias sensoriales y de cortezas premotoras.", "Los axones del sistema lateral del tronco encefálico hacen sinapsis con neuronas sensoriales medulares."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q9", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Durante el reflejo de retirada de un miembro frente a un estímulo nocivo, es correcto afirmar que:",
    options: ["Se contraen los músculos extensores de ambos miembros.", "Solo se modifica la actividad del miembro contralateral al estimulado.", "La información sensorial alcanza las motoneuronas a través de una vía polisináptica."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q10", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Respecto a los husos neuromusculares y a los órganos tendinosos de Golgi, es correcto afirmar que:",
    options: ["El huso neuromuscular detecta cambios en la tensión del tendón.", "El órgano tendinoso de Golgi detecta la tensión generada en el músculo.", "Un aumento de la longitud muscular disminuye la descarga aferente del huso neuromuscular."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q11", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "autonomo", materia: 'neuro',
    question: "Con respecto a la división simpática del sistema nervioso autónomo, marque la opción correcta:",
    options: ["La neurona preganglionar libera noradrenalina.", "El intestino delgado carece de inervación simpática.", "La vasoconstricción periférica es mediada por receptores alfa adrenérgicos."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q12", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "autonomo", materia: 'neuro',
    question: "Con respecto a la división parasimpática del sistema nervioso autónomo, marque la opción correcta:",
    options: ["Tanto a nivel preganglionar como posganglionar el neurotransmisor liberado es la acetilcolina.", "Cuando la actividad de esta división se intensifica, aumenta la frecuencia cardíaca.", "La actividad de esta división se intensifica en situación de lucha o huida."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q13", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "histologia-neuronal", materia: 'neuro',
    question: "De acuerdo a la cantidad de prolongaciones, una neurona estrellada se clasifica como:",
    options: ["Seudounipolar", "Bipolar", "Multipolar"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q14", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "histologia-neuronal", materia: 'neuro',
    question: "El neuropilo se caracteriza por ser el lugar:",
    options: ["de mayor densidad sináptica", "de mayor cantidad de fibras mielínicas", "donde se localizan los somas neuronales"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q15", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "mielina-nervio", materia: 'neuro',
    question: "Los oligodendrocitos son las células encargadas de formar las vainas de mielina:",
    options: ["Solo en la sustancia blanca", "Solo en la sustancia gris", "En ambas sustancias"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q16", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "medula-espinal", materia: 'neuro',
    question: "Las motoneuronas de la médula espinal se localizan en:",
    options: ["El asta ventral o anterior", "El asta dorsal o posterior", "El cordón ventral o anterior"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q17", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "cerebelo", materia: 'neuro',
    question: "Con respecto a las neuronas de Purkinje de la corteza cerebelosa:",
    options: ["Son la única eferencia de la corteza", "Su axón forma parte de las fibras paralelas", "Su árbol dendrítico se extiende por la capa granulosa"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q18", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "cerebelo", materia: 'neuro',
    question: "Con respecto a los glomérulos cerebelosos:",
    options: ["Se localizan en la capa molecular", "En ellos hacen sinapsis las dendritas de los granos", "Las fibras trepadoras hacen sinapsis en estas estructuras"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q19", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "cerebelo", materia: 'neuro',
    question: "Las células grano del arquicortex:",
    options: ["Son un tipo particular de célula glial", "Se localizan en el cuerno o asta de Amon", "Todas sus dendritas se dirigen a la capa molecular"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q20", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "corteza-cerebral", materia: 'neuro',
    question: "Las neuronas piramidales de la capa V de la neocorteza",
    options: ["Están ausentes en la corteza sensorial", "Su axón puede llegar a hacer sinapsis en la médula espinal", "Son neuronas inhibitorias que utilizan acetilcolina como neurotransmisor"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P1-Q21", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "medula-espinal", materia: 'neuro',
    question: "Con respecto a las neuronas de los ganglios de la raíz dorsal de la médula espinal (también conocidos como ganglios espinales o raquídeos):",
    options: ["Son de tipo seudounipolares", "Conducen información motora", "En la mayoría de los casos su prolongación periférica es amielínica."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q22", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "glia", materia: 'neuro',
    question: "Con respecto a los astrocitos del SNC",
    options: ["Sus precursores migran desde la médula ósea.", "Son responsables de la formación de la mielina.", "Inducen la formación de la barrera hematoencefálica."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P1-Q23", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "Con respecto a los corpúsculos de Paccini:",
    options: ["Son receptores encapsulados.", "Solo se localizan en la dermis superficial", "Son responsables de la sensibilidad discriminativa"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P1-Q24", source: 'exam', exam: "Prototipo 1er periodo (22/11)", topic: "mielina-nervio", materia: 'neuro',
    question: "Con respecto a los nodos de Ranvier del sistema nervioso periférico:",
    options: ["Están presentes en fibras amielínicas.", "Están cubiertos por prolongaciones astrocitarias.", "Permiten la conducción del impulso nervioso a mayor velocidad"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q1", source: 'exam', exam: "Prototipo (23/11)", topic: "histologia-neuronal", materia: 'neuro',
    question: "Las dendritas de las neuronas estrelladas del sistema nervioso central, generalmente:",
    options: ["se distribuyen de forma seudomonopolar", "se ramifican cerca del soma", "carecen de espinas"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q2", source: 'exam', exam: "Prototipo (23/11)", topic: "glia", materia: 'neuro',
    question: "Luego de un daño agudo al sistema nervioso central, ¿cuál de los siguientes tipos celulares adquiere morfología ameboide y se desplaza hacia el sitio dañado?",
    options: ["microglías", "astrocitos fibrosos", "astrocitos protoplasmáticos"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q3", source: 'exam', exam: "Prototipo (23/11)", topic: "glia", materia: 'neuro',
    question: "Para identificar un astrocito ¿cuál de los siguientes elementos esperamos encontrar en su citoplasma en forma abundante?",
    options: ["grumos de Nissl", "inclusiones de glucógeno", "lisosomas y fagolisosomas"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q4", source: 'exam', exam: "Prototipo (23/11)", topic: "glia", materia: 'neuro',
    question: "¿Cuál de los siguientes tipos celulares forma parte de la membrana limitante glial en el sistema nervioso central?",
    options: ["células satélite", "microglía", "astrocitos"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q5", source: 'exam', exam: "Prototipo (23/11)", topic: "mielina-nervio", materia: 'neuro',
    question: "El tejido conjuntivo que rodea directamente cada fibra nerviosa en un nervio se denomina:",
    options: ["epineuro", "perineuro", "endoneuro"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q6", source: 'exam', exam: "Prototipo (23/11)", topic: "medula-espinal", materia: 'neuro',
    question: "Se tomaron varias imágenes de un preparado histológico de médula espinal, pero se mezclaron las etiquetas. En una de las imágenes se observan astrocitos fibrosos y oligodendrocitos. ¿Cuál de las siguientes etiquetas le pondría?",
    options: ["lámina IX de Rexed", "sustancia gelatinosa de Rolando", "cordón posterior, fascículo Gracilis"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q7", source: 'exam', exam: "Prototipo (23/11)", topic: "medula-espinal", materia: 'neuro',
    question: "En un paciente que acude a la emergencia por un accidente doméstico con una sierra, se constata una lesión en el nervio que llega al dedo pulgar y se logra mediante sutura unir los extremos proximal y distal. ¿Cuál de los siguientes eventos esperamos que ocurra?",
    options: ["Degeneración del segmento distal de los axones cortados y es posible la regeneración a partir del cabo proximal", "Muerte de las neuronas de la médula espinal involucradas y formación de una cicatriz persistente", "Proliferación de oligodendrocitos en el sitio de lesión"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q8", source: 'exam', exam: "Prototipo (23/11)", topic: "mielina-nervio", materia: 'neuro',
    question: "¿Cuál de los siguientes receptores presenta su terminal nerviosa amielínica rodeada por láminas concéntricas de células de Schwann y fibroblastos modificados?",
    options: ["Corpúsculo de Pacini.", "Corpúsculo de Ruffini.", "Corpúsculo de Meissner."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q9", source: 'exam', exam: "Prototipo (23/11)", topic: "corteza-cerebral", materia: 'neuro',
    question: "En un preparado de un sector del cerebro, a nivel de la neocorteza se distingue una capa donde abundan grandes neuronas de cuyo soma se extienden un grueso tronco dendrítico orientado hacia la superficie y múltiples dendritas basales. También desde la base del soma, se desprende el axón que se introduce en la sustancia blanca para dirigirse hacia sectores extracorticales. Esta capa corresponde a la:",
    options: ["granulosa externa.", "piramidal interna.", "molecular"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q10", source: 'exam', exam: "Prototipo (23/11)", topic: "cerebelo", materia: 'neuro',
    question: "Las eferencias de la corteza cerebelosa corresponden al axón de:",
    options: ["las células granulares", "las neuronas de Purkinje", "las neuronas en cesto de Cajal"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q11", source: 'exam', exam: "Prototipo (23/11)", topic: "cerebelo", materia: 'neuro',
    question: "¿A qué corresponden las fibras musgosas en la corteza cerebelosa?",
    options: ["son axones de las neuronas granulares", "son las dendritas de las neuronas de Golgi", "son axones de neuronas cuyo soma se encuentra fuera de la corteza"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q12", source: 'exam', exam: "Prototipo (23/11)", topic: "corteza-cerebral", materia: 'neuro',
    question: "¿Cuál de las siguientes células son las neuronas principales del asta de Ammon del arquicortex?",
    options: ["Célula grano", "Neuronas polimorfas de la capa III", "Neuronas piramidales (o piramidales dobles)"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q13", source: 'exam', exam: "Prototipo (23/11)", topic: "organizacion-sn", materia: 'neuro',
    question: "Con respecto a la organización del sistema nervioso central:",
    options: ["El cerebelo ejerce control directo sobre la hipófisis.", "El tronco encefálico controla funciones autónomas vitales.", "El tálamo es el principal centro regulador de la homeostasis."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q14", source: 'exam', exam: "Prototipo (23/11)", topic: "sinapsis", materia: 'neuro',
    question: "Con respecto a la integración sináptica:",
    options: ["Los potenciales de acción se suman en la célula presináptica.", "Los potenciales postsinápticos inhibitorios pueden sumarse entre sí.", "Los potenciales postsinápticos se pueden sumar en el tiempo, pero no en el espacio."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q15", source: 'exam', exam: "Prototipo (23/11)", topic: "autonomo", materia: 'neuro',
    question: "La estimulación del sistema nervioso parasimpático promueve:",
    options: ["La digestión.", "Un aumento de la presión arterial.", "Un aumento de la frecuencia respiratoria."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q16", source: 'exam', exam: "Prototipo (23/11)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "¿Qué caracteriza a los receptores de adaptación lenta en comparación con los de adaptación rápida?",
    options: ["Generan potenciales de acción sólo al inicio y al final de un estímulo.", "No generan potenciales de acción frente a estímulos constantes prolongados", "Mantienen la generación de potenciales de acción durante la duración de un estímulo constante."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-PB-Q17", source: 'exam', exam: "Prototipo (23/11)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "La transducción de un estímulo sensorial se lleva a cabo en:",
    options: ["El receptor sensorial.", "El axón de la neurona aferente sensorial primaria.", "El soma de una neurona sensorial de segundo orden."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q18", source: 'exam', exam: "Prototipo (23/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Cuál de los siguientes componentes es indispensable para que ocurra un acto motor reflejo?",
    options: ["La participación de las cortezas cerebrales para iniciar el movimiento.", "Un estímulo sensorial que active receptores en la piel o músculos.", "La contracción de múltiples músculos de forma voluntaria."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q19", source: 'exam', exam: "Prototipo (23/11)", topic: "control-motor", materia: 'neuro',
    question: "En relación a la organización de las cortezas motoras:",
    options: ["Presentan organización somatotópica.", "Es clave para la ejecución de actos motores reflejos.", "Envían las respuestas motoras a las cortezas somatosensoriales."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q20", source: 'exam', exam: "Prototipo (23/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Cuál de las siguientes afirmaciones es correcta respecto al reflejo de flexión de retirada en el miembro inferior?",
    options: ["Su modulación involucra una vía neural polisináptica.", "Su finalización es controlada por motoneuronas de la corteza motora.", "El músculo extensor del miembro estimulado y del miembro opuesto se contraen simultáneamente."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-PB-Q21", source: 'exam', exam: "Prototipo (23/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Cuál de las siguientes variables es sensada por el huso neuromuscular?",
    options: ["La tensión muscular.", "La longitud del músculo.", "La excitabilidad de una fibra muscular."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-PB-Q22", source: 'exam', exam: "Prototipo (23/11)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Cuando el músculo es sometido a un aumento progresivo de fuerza, ¿cuál es la última unidad motora en ser reclutada?",
    options: ["Las de contracción rápida y fatigables.", "Las resistentes a la fatiga y de contracción lenta.", "Las de contracción rápida y resistentes a la fatiga."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q1", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "sinapsis", materia: 'neuro',
    question: "En dos neuronas comunicadas mediante uniones GAP:",
    options: ["El paso de corriente es dependiente de la superación del umbral en una de las neuronas.", "Es esperable que haya un retraso en la sinapsis de 10 ms.", "Se pueden transmitir corrientes hiperpolarizantes."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q2", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "Los mecanorreceptores del sistema somatosensorial son sensibles a",
    options: ["Deformaciones del tejido.", "Foto-pigmentos.", "Calor."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q3", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "Con respecto a las cortezas somatosensoriales primarias, ¿cuál de las siguientes afirmaciones es correcta?",
    options: ["Reciben información del tálamo.", "No tienen organización somatotópica.", "Reciben información de las cortezas motoras."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q4", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Considerando que las unidades motoras se clasifican en: unidades motoras de contracción lenta y resistentes a la fatiga (LR), de contracción rápida y resistentes a la fatiga (RR), y de contracción rápida y fatigables (RF), ¿en qué orden se reclutan cuando un músculo debe realizar fuerza?",
    options: ["LR – RR – RF.", "LR– RF – RR.", "RR – LR– RF."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q5", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "control-motor", materia: 'neuro',
    question: "La marcha considera un movimiento:",
    options: ["De inicio involuntario.", "Reflejo durante el mantenimiento.", "De ejecución rápida comparada con un reflejo."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q6", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Durante el reflejo de flexión del miembro inferior, ¿cuál de las siguientes afirmaciones es correcta?",
    options: ["Se activan los músculos flexores en ambos miembros inferiores.", "Se inhiben los músculos extensores de ambos miembros inferiores.", "Se activan únicamente los músculos flexores del miembro estimulado."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q7", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Qué ocurre frente a un aumento en la tensión muscular?",
    options: ["Aumenta la frecuencia de descarga del huso neuromuscular.", "Aumenta la frecuencia de descarga del órgano tendinoso de Golgi.", "Aumenta la amplitud de los potenciales de acción de la aferente sensorial primaria."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q8", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "autonomo", materia: 'neuro',
    question: "La noradrenalina puede ser liberada desde:",
    options: ["La terminal preganglionar simpática.", "La neurona postganglionar simpática.", "La terminal preganglionar parasimpática."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q9", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "autonomo", materia: 'neuro',
    question: "¿Cuál es de los siguientes receptores es el predominante a nivel ganglionar del sistema nervioso parasimpático?",
    options: ["Nicotínicos.", "Adrenérgicos.", "GABAérgicos."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q10", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "medula-espinal", materia: 'neuro',
    question: "Con respecto a las técnicas para estudiar el sistema nervioso:",
    options: ["La hematoxilina-eosina en cortes histológicos permite la visualización de espinas dendríticas", "Las técnicas mieloarquitecturales permiten diferenciar la sustancia gris de la sustancia blanca", "La impregnación argéntica de Golgi permite identificar las neuronas por su núcleo eucromático"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q11", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "sinapsis", materia: 'neuro',
    question: "¿Cuál de los siguientes tipos celulares participa en la recaptación de neurotransmisores a nivel de las sinapsis en el sistema nervioso central?",
    options: ["microglías ameboides", "oligodendrocitos maduros", "astrocitos protoplasmáticos"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q12", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "glia", materia: 'neuro',
    question: "En un laboratorio están estudiando una muestra de cerebro y desean identificar distintos tipos celulares mediante inmunohistoquímica. Se cuenta con algunos anticuerpos primarios. Para detectar a los astrocitos deberíamos seleccionar anticuerpos que reconozcan cuál de las siguientes moléculas:",
    options: ["proteína ácida fibrilar glial (GFAP)", "neurofilamentos de cadena liviana", "proteína básica de mielina"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q13", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "mielina-nervio", materia: 'neuro',
    question: "En un nervio periférico:",
    options: ["Los nodos de Ranvier son sectores de mielina compacta.", "Cada internodo mielínico está formado por varias células de Schwann.", "Los axones amielínicos se encuentran invaginados en surcos de las células de Schwann."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q14", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Con respecto a las fibras intrafusales del huso neuromuscular:",
    options: ["Están rodeadas por una cápsula multilaminar", "Su inervación es solamente motora, careciendo de inervación sensitiva", "La disposición de sus núcleos es diferente a la de las fibras extrafusales"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q15", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "medula-espinal", materia: 'neuro',
    question: "Con respecto a la médula espinal:",
    options: ["Los somas neuronales de mayor tamaño se localizan en el asta ventral", "La mayor parte de la sustancia blanca está formada por fibras de disposición transversal", "Los somas neuronales cuyo axón se dirige a la periferia se localizan principalmente en el asta dorsal"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q16", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "medula-espinal", materia: 'neuro',
    question: "Luego de una lesión de médula espinal que afecta la sustancia blanca a nivel lumbar, ¿cuál de las siguientes eventos esperamos que ocurra a nivel del tejido en el sitio de la lesión?",
    options: ["Muerte de las motoneuronas en la médula cervical", "Proliferación de astrocitos y formación de cicatriz glial", "Reparación de las fibras nerviosas a partir de las células de Schwann"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q17", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "cerebelo", materia: 'neuro',
    question: "Con respecto a las neuronas de la corteza cerebelosa:",
    options: ["las neuronas de Purkinje son las neuronas principales", "las neuronas de Golgi tienen su soma en la capa molecular", "las células en cesto son el principal componente de los glomérulos cerebelosos"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q18", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "cerebelo", materia: 'neuro',
    question: "Con respecto a la glía de Bergmann de la corteza cerebelosa:",
    options: ["Son un tipo de microglía típica de esta región del sistema nervioso", "La mayor parte de sus prolongaciones se encuentran en la capa molecular", "Su soma se ubica fundamentalmente en la parte profunda de la capa granular"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P2-Q19", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "cerebelo", materia: 'neuro',
    question: "Acerca de las fibras de la corteza cerebelosa:",
    options: ["Las fibras trepadoras son los axones de los granos", "Las fibras paralelas son fibras aferentes provenientes de los núcleos cerebelosos", "Las fibras musgosas son fibras aferentes que hacen sinapsis en la capa granular"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P2-Q20", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "corteza-cerebral", materia: 'neuro',
    question: "Con respecto al neocórtex cerebral:",
    options: ["En todas sus capas se encuentran neuronas de tipo multipolar", "En la capa III los somas predominantes son de morfología fusiforme", "La capa I es la que contiene mayor cantidad de neuronas piramidales"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P2-Q21", source: 'exam', exam: "Prototipo 2do periodo (19/12)", topic: "corteza-cerebral", materia: 'neuro',
    question: "¿Cómo se denomina la capa I del arquicortex?",
    options: ["piramidal", "polimorfa", "molecular"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q1", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "En una neurona multipolar:",
    options: ["el axón se distingue porque aumenta su diámetro a medida que se aleja de soma", "el sector inicial de las dendritas es más delgado que el del axón", "las dendritas se ramifican cerca del soma"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q2", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "glia", materia: 'neuro',
    question: "Luego de un daño al sistema nervioso central, ¿qué tipo celular adquiere capacidad fagocítica?",
    options: ["microglías", "astrocitos fibrosos", "astrocitos protoplasmáticos"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q3", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "glia", materia: 'neuro',
    question: "¿Cuál de los siguientes componentes es típico encontrar en el citoplasma de una microglía?",
    options: ["grumos de Nissl", "lisosomas y fagolisosomas", "filamentos intermedios formados por GFAP"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q4", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "¿Cuál de los siguientes tipos celulares tiene prolongaciones terminales sobre los vasos sanguíneos en el sistema nervioso central?",
    options: ["neuronas", "astrocitos", "microglía"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q5", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "mielina-nervio", materia: 'neuro',
    question: "¿Cómo se denomina el tejido conjuntivo que rodea directamente cada fibra nerviosa en un nervio?",
    options: ["epineuro", "perineuro", "endoneuro"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q6", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "medula-espinal", materia: 'neuro',
    question: "¿Cuál de las siguientes opciones es correcta con respecto a las motoneuronas de la médula espinal?",
    options: ["sus dendritas son poco ramificadas y sin espinas", "su axón tiene mielina formada en parte por oligodendrocitos y en parte por células de Schwann", "su soma tiene ribosomas que no llegan a conformar grumos de Nissl visibles con microscopía óptica"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q7", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "medula-espinal", materia: 'neuro',
    question: "¿Cuál de los siguientes segmentos de la médula espinal tiene una mayor cantidad de fibras en la sustancia blanca?",
    options: ["cervical 2", "lumbar 5", "torácico 12"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q8", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Cómo se denominan los receptores formados por un terminal nervioso rodeado de múltiples láminas conjuntivas concéntricas?",
    options: ["corpúsculo de Meissner", "corpúsculo de Paccini", "huso neuromuscular"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q9", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "Si se corta un axón largo, ¿en qué caso existe mayor posibilidad de regeneración?",
    options: ["cuando no ocurre degeneración del segmento distal", "cuando la lesión es lejos del soma neuronal", "cuando no ocurre reacción local en la lesión"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q10", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "cerebelo", materia: 'neuro',
    question: "¿En qué capa de la corteza cerebelosa se localizan los glomérulos cerebelosos?",
    options: ["capa granular", "capa molecular", "capa de Purkinje"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q11", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "cerebelo", materia: 'neuro',
    question: "¿Con qué parte de las células granulares contactan las fibras aferentes musgosas?",
    options: ["axón", "soma", "dendritas"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q12", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "corteza-cerebral", materia: 'neuro',
    question: "¿En qué capa del neocórtex del área motora primaria se localizan los somas de las neuronas cuyo axón alcanza la médula espinal?",
    options: ["capa I", "capa IV", "capa V"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q13", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "membrana-potencial", materia: 'neuro',
    question: "Para que se desarrolle un potencial de acción en el cono axónico, ¿Cuál de los siguientes eventos ocurre primero?",
    options: ["Despolarización supraumbral.", "Apertura de canales de K+ dependientes de voltaje.", "Inactivación de los canales de Na+ dependientes de voltaje."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q14", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "membrana-potencial", materia: 'neuro',
    question: "El sentido de propagación de un potencial de acción que se desarrolló en el cono axónico se verá favorecida por:",
    options: ["La hiperpolarización del potencial de membrana en el frente de propagación.", "La inactivación de los canales de Na+ dependientes de voltaje en el frente de propagación.", "La cinética de cierre lenta de los canales de K+ dependientes de voltaje en la cola de propagación."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q15", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "membrana-potencial", materia: 'neuro',
    question: "Cuando el potencial de membrana de una neurona permanece en reposo:",
    options: ["La bomba de Na+/K+ ATPasa permanece inactiva.", "Los canales de Na+ dependientes de voltaje se encuentran abiertos.", "El flujo neto de iones entre el compartimiento intra y extracelular es 0."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q16", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "Respecto a las vías centrales del sistema somatosensorial nociceptivo:",
    options: ["La tercera neurona de esta vía se encuentra a nivel medular.", "La neurona aferente primaria de esta vía alcanza cortezas motoras.", "Alcanza las cortezas somatosensoriales a través de una vía contralateral."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q17", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "¿Cuál de los siguientes receptores táctiles se encuentran ubicados en la profundidad de la piel y presentan adaptación rápida?",
    options: ["Corpúsculos de Pacini.", "Corpúsculo de Meissner.", "Receptor disco de Merkel."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q18", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "control-motor", materia: 'neuro',
    question: "Los movimientos rítmicos se caracterizan por una de las siguientes características:",
    options: ["Su inicio es involuntario.", "Su finalización es voluntaria.", "Su ejecución solo depende de aferencias y eferencias medulares."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q19", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "control-motor", materia: 'neuro',
    question: "En relación a las vías centrales y cortezas motoras que modulan los diferentes tipos de movimientos motores:",
    options: ["Las cortezas motoras carecen de aferencias de cortezas sensoriales.", "Los axones del haz corticoespinal pueden enviar proyecciones al tronco encefálico.", "Los axones motores del haz del sistema lateral del tronco encefálico hacen sinapsis con neuronas sensoriales a nivel medular."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q20", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "¿Cuál de los siguientes eventos ocurre durante el reflejo de retirada de un miembro inferior frente a un estímulo nocivo?",
    options: ["Se contrae el músculo extensor del miembro opuesto al estimulado.", "La información sensorial alcanza vías motoras a través de una vía monosináptica.", "Las vías sensoriales que envían la información al sistema nervioso central solo modulan la actividad del miembro estimulado."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3A-Q21", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "Respecto a los husos neuromusculares y a los órganos tendinosos de Golgi:",
    options: ["Los husos neuromusculares sensan un aumento de la tensión del tendón.", "El órgano tendinoso de Golgi sensa el estiramiento de las fibras musculares.", "Un aumento en la tensión del tendón aumenta la actividad de la aferente sensorial del órgano tendinoso de Golgi."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3A-Q22", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "autonomo", materia: 'neuro',
    question: "La activación del sistema nervioso parasimpático tiene como consecuencia:",
    options: ["La dilatación de las pupilas.", "Una disminución de la frecuencia cardíaca.", "Una relajación de la musculatura lisa intestinal."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3A-Q23", source: 'exam', exam: "Prototipo 3er periodo (14/02)", topic: "autonomo", materia: 'neuro',
    question: "En el sistema nervioso autónomo, la sinapsis ganglionar tiene una de las siguientes características:",
    options: ["La división simpática está mediada por noradrenalina y sus receptores son principalmente adrenérgicos.", "Está mediada por noradrenalina en la división parasimpática y acetilcolina en la división simpática.", "En ambas divisiones los receptores son principalmente colinérgicos."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q1", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "En cuanto a las propiedades electrofisiológicas de las neuronas:",
    options: ["Los potenciales receptoriales generalmente se propagan sin decremento a lo largo del axón.", "La generación del potencial de acción no depende de la apertura de canales voltaje- dependiente.", "En ausencia de Ca++ intracelular en la terminal presináptica, no es posible observar un potencial postsináptico excitatorio."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q2", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "autonomo", materia: 'neuro',
    question: "Si usted se encuentra frente a una situación de peligro repentina, es esperable que:",
    options: ["Las pupilas aumenten su diámetro.", "Se estimule el sistema nervioso parasimpático.", "Se promueva el almacenamiento de nutrientes."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3B-Q3", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "El hipotálamo es un área crucial en el control de:",
    options: ["la memoria.", "la regulación de los ritmos circadianos.", "la coordinación del acto motor voluntario."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3B-Q4", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "¿Cuál de las siguientes características es propia la sinapsis eléctrica?",
    options: ["Bidireccionalidad.", "Gran retardo sináptico.", "La activación de receptores postsinápticos."],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3B-Q5", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "En relación a los receptores de tipo ionotrópicos:",
    options: ["Su activación estimula la producción directa de proteínas G.", "Son macromoléculas distintas de los canales iónicos a los que afectan.", "Generan respuestas postsinápticas más rápidas que lo receptores metabotrópicos."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q6", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "reflejos-propiocepcion", materia: 'neuro',
    question: "En cuanto a los actos motores reflejos:",
    options: ["El reflejo flexor o de retirada se caracteriza por ser monosináptico.", "El reflejo miotático se activa cuando el músculo se estira más allá de su estado de referencia.", "El reflejo miotático es desencadenado por estímulos nociceptivos sobre la superficie corporal."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3B-Q7", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "control-motor", materia: 'neuro',
    question: "Con respecto a los actos motores voluntarios:",
    options: ["Se caracterizan por ser respuestas innatas que mantenemos invariadas a lo largo de nuestras vidas.", "Se caracterizan por ofrecer una respuesta estereotipada frente a un estímulo determinado.", "Su iniciación puede carecer de un estímulo externo que lo desencadene."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q8", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "Los sistemas sensoriales codifican la intensidad de un estímulo en función de:",
    options: ["El tipo de receptor activado.", "El tamaño del campo receptorial.", "El número de receptores activados."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q9", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "vias-somatosensoriales", materia: 'neuro',
    question: "La distancia por la que deben estar separados dos estímulos táctiles para percibirse como dos estímulos individuales es menor en:",
    options: ["las orejas.", "la espalda.", "la punta de los dedos."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q10", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "La activación de los receptores postsinápticos metabotrópicos provoca:",
    options: ["Respuestas postsinápticas rápidas.", "La producción de segundos mensajeros.", "Un cambio conformacional directo en los canales iónicos."],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3B-Q11", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "glia", materia: 'neuro',
    question: "¿Qué tipo celular del tejido nervioso posee prolongaciones llamadas pies terminales que rodean los vasos sanguíneos?",
    options: ["astrocito", "microglía", "oligodendrocito"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3B-Q12", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "Las neuronas de mayor tamaño del sistema nervioso central se caracterizan por presentar:",
    options: ["axón corto", "núcleo heterocromático", "grumos de Nissl en el soma"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q13", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "Indique a qué estructuras celulares corresponden los grumos de Nissl.",
    options: ["neurofilamentos", "vesículas sinápticas", "RER y polirribosomas"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q14", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "histologia-neuronal", materia: 'neuro',
    question: "¿Cómo clasificaría desde el punto de vista morfológico a una neurona sensitiva de un ganglio raquídeo?",
    options: ["Bipolar", "Multipolar", "Pseudounipolar"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q15", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "¿Cómo se transporta una vesícula conteniendo neurotransmisores desde el soma a la terminal sináptica?",
    options: ["Mediante transporte retrógrado utilizando dineínas", "Deslizándose anclada a filamentos de actina", "Unida a microtúbulos a través de kinesinas"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q16", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "mielina-nervio", materia: 'neuro',
    question: "En los axones mielínicos del sistema nervioso central:",
    options: ["existe una lámina basal que los rodea", "cada segmento internodal es mielinizado por una célula de Schwann", "la región de los nodos de Ranvier contacta con prolongaciones astrocitarias"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q17", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "mielina-nervio", materia: 'neuro',
    question: "En el sistema nervioso periférico:",
    options: ["los axones amielínicos están rodeados por citoplasma de la célula de Schwann", "en la región de los nodos de Ranvier los axones contactan directamente con el endoneuro", "una célula de Schwann extiende numerosas prolongaciones que rodean varios segmentos internodales"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3B-Q18", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "cerebelo", materia: 'neuro',
    question: "De las siguientes regiones de la corteza cerebral, ¿cuál se asemeja más en su estructura a la corteza cerebelosa?",
    options: ["Neocortex", "Paleocortex", "Arquicortex"],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q19", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "cerebelo", materia: 'neuro',
    question: "Con respecto a las neuronas de Purkinje de la corteza cerebelosa, marque la opción correcta:",
    options: ["Su soma se localiza en la capa granular.", "Son neuronas de axón corto (interneuronas).", "Su arborización dendrítica apical se distribuye en la capa molecular."],
    correctIndex: 2,
    explanation: null,
  },
  {
    id: "N-P3B-Q20", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "sinapsis", materia: 'neuro',
    question: "¿Cuál de los siguientes tipos de neuronas NO utiliza glutamato como neurotransmisor?",
    options: ["Neurona piramidal del cerebro", "Neurona de Purkinje del cerebelo", "Neurona grano (o granular) del cerebelo"],
    correctIndex: 1,
    explanation: null,
  },
  {
    id: "N-P3B-Q21", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "medula-espinal", materia: 'neuro',
    question: "En la médula espinal, ¿dónde se ubican los somas neuronales de mayor tamaño?",
    options: ["En el asta anterior de la médula espinal", "En el asta posterior de la médula espinal", "En la sustancia gris central periependimaria"],
    correctIndex: 0,
    explanation: null,
  },
  {
    id: "N-P3B-Q22", source: 'exam', exam: "Prototipo 3er periodo (17/02)", topic: "receptores-sensoriales", materia: 'neuro',
    question: "En la piel, los receptores sensoriales que tienen mayor tamaño son los receptores",
    options: ["de Meissner", "de Merkel", "de Pacini"],
    correctIndex: 2,
    explanation: null,
  },
];
