/**
 * pKapp - Banco de preguntas - Cardiovascular y Respiratorio
 *
 * El contenido de estas preguntas NO pertenece a pKapp ni a Agustín Frusto:
 * se basa en material de estudio de terceros, cuyos derechos pertenecen a sus
 * autores originales. Se reproduce sin fines comerciales y con fines
 * exclusivamente educativos (uso NO comercial).
 * Reclamos de derechos: agustinfrusto@gmail.com
 */
// Estructura: { id, source, exam, topic, materia: 'cyr', question, options, correctIndex, explanation }
export const QUESTIONS = [
  // ============== PROTOTIPO 1 ==============
  {
    id: 'CYR-PROTOTIPO-1-Q25',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'Las arterias musculares se caracterizan por poseer:',
    options: [
      'Un endotelio más alto que las arterias elásticas',
      'Un diámetro mayor que las de las arterias elásticas.',
      'Una limitante elástica interna más evidente que la de las arterias elásticas',
    ],
    correctIndex: 2,
    explanation: 'La limitante elástica interna es una lámina gruesa y bien definida en la arteria muscular, mientras que en la elástica queda disimulada entre las numerosas láminas de la túnica media. El endotelio es plano en ambas y el calibre de las elásticas es mayor, no menor.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'En los capilares sanguíneos se produce el intercambio de nutrientes, ¿qué elementos NO se encuentran formado su pared?',
    options: [
      'Membrana basal',
      'Células endoteliales.',
      'Células musculares lisas.',
    ],
    correctIndex: 2,
    explanation: 'La pared capilar está formada solo por endotelio y membrana basal; el músculo liso aparece recién a nivel arteriolar y venular. Esa pared mínima es justamente lo que permite el intercambio.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q27',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'El miocardio específico se diferencia del miocardio inespecífico porque: (indique lo correcto)',
    options: [
      'Está constituido por células que se originan en el endodermo.',
      'Posee mayor cantidad de uniones comunicantes (gap).',
      'No posee miofilamentos.',
    ],
    correctIndex: 1,
    explanation: 'El miocardio específico se distingue por su abundancia de uniones comunicantes, que acoplan eléctricamente las células y permiten la conducción rápida del impulso. Su origen es mesodérmico y conserva miofilamentos, aunque escasos.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q28',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'En el intersticio pulmonar en condiciones normales se puede encontrar',
    options: [
      'Macrófagos alveolares',
      'Abundantes fibras elásticas',
      'Abundantes fibras colágenas',
    ],
    correctIndex: 1,
    explanation: 'El intersticio pulmonar normal es rico en fibras elásticas, responsables del retroceso elástico del pulmón. Los macrófagos alveolares habitan la luz del alvéolo, no el intersticio, y el colágeno abundante corresponde a situaciones de fibrosis.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q29',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿En el epitelio de cuál sector del aparato respiratorio se encuentran las células de Clara?',
    options: [
      'En la laringe',
      'En los bronquios',
      'En los bronquiolos',
    ],
    correctIndex: 2,
    explanation: 'Las células de Clara son propias del epitelio bronquiolar, donde secretan el componente proteico del surfactante y ya no hay células caliciformes. La laringe y los bronquios están tapizados por epitelio respiratorio ciliado.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: '¿Qué sucede en el sistema respiratorio, cuando no existe ni entrada ni salida de aire?',
    options: [
      'La presión transmural toracopulmonar es negativa.',
      'La presión alveolar es igual a la presión atmosférica.',
      'Hay un flujo aéreo en contra del gradiente de presión.',
    ],
    correctIndex: 1,
    explanation: 'Sin flujo aéreo no hay gradiente que lo genere, de modo que la presión alveolar iguala a la atmosférica. La presión transmural toracopulmonar es la que se anula en esa condición, y un flujo en contra del gradiente es imposible.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q33',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: '¿Qué implicancias tiene la generación de un neumotórax en el sistema respiratorio?',
    options: [
      'El tórax y el pulmón se comprimen.',
      'El pulmón y el tórax se disocian y tienden a alcanzar su equilibrio mecánico.',
      'Es necesario la contracción de los músculos espiratorios para evitar el colapso pulmonar.',
    ],
    correctIndex: 1,
    explanation: 'En el neumotórax entra aire a la cavidad pleural y se pierde la presión negativa que mantenía acoplados pulmón y tórax: cada uno vuelve a su posición de equilibrio, el pulmón colapsando y la caja torácica expandiéndose. No se comprimen ambos ni hace falta contracción espiratoria alguna.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q34',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Respecto al potencial generado por un dipolo que se registra en un punto P suficientemente alejado del mismo:',
    options: [
      'Tiene una relación directamente proporcional con el producto del valor absoluto de la carga (|q|) y el brazo del dipolo (distancia entre ambas cargas del dipolo).',
      'Es directamente proporcional al coseno del ángulo entre el semieje negativo y la recta r (recta que une el centro del dipolo con el punto P).',
      'Es menor, cuanto más separadas estén las cargas entre sí, es decir, cuanto mayor es el brazo del dipolo.',
    ],
    correctIndex: 0,
    explanation: 'El potencial que genera un dipolo en un punto lejano es proporcional a su momento dipolar, o sea al producto de la carga por el brazo. Por eso crece, y no disminuye, cuando las cargas se separan más, y el coseno se mide respecto del semieje positivo.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q35',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto al trazado electrocardiográfico:',
    options: [
      'La onda T representa la entrada de calcio al miocito ventricular por canales de calcio tipo T.',
      'Los segmentos constituyen partes isoeléctricas y los intervalos están compuestos por ondas y segmentos.',
      'La fase de despolarización del potencial de acción del nódulo sinusal se haya representada por la onda P.',
    ],
    correctIndex: 1,
    explanation: 'Los segmentos del trazado son tramos isoeléctricos y los intervalos abarcan ondas junto con segmentos. La onda T corresponde a la repolarización ventricular, y la despolarización del nódulo sinusal no genera deflexión visible en el trazado de superficie.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q36',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'En individuos ancianos la presión arterial se ve incrementada principalmente por una disminución en:',
    options: [
      'el gasto cardíaco',
      'la distensibilidad de las arterias',
      'la resistencia vascular periférica',
    ],
    correctIndex: 1,
    explanation: 'Con la edad las arterias pierden elastina y ganan colágeno, y esa caída de la distensibilidad hace que el mismo volumen eyectado genere un pico de presión mayor. El gasto cardíaco tiende a disminuir y la resistencia periférica no es el determinante principal en este caso.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q37',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Si existe una gran rigidez arterial, el flujo sanguíneo a nivel capilar ocurre:',
    options: [
      'en forma constante',
      'principalmente en sístole',
      'tanto en sístole como en diástole',
    ],
    correctIndex: 1,
    explanation: 'Una arteria rígida no puede almacenar volumen en sístole ni devolverlo en diástole, de modo que el efecto amortiguador se pierde y el flujo capilar se concentra en la sístole. El flujo constante es justamente lo que aporta la elasticidad arterial normal.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q38',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Con respecto al intercambio gaseoso:',
    options: [
      'El O2 es más difusible que el CO2.',
      'El intercambio gaseoso de O2 y CO2 a través de la barrera alveolo-capilar se da por difusión facilitada.',
      'La composición de O2 alveolar está determinada por el equilibrio entre el agregado de O2 por la ventilación alveolar y su eliminación por flujo sanguíneo.',
    ],
    correctIndex: 2,
    explanation: 'La PO2 alveolar resulta del balance entre el oxígeno que aporta la ventilación y el que retira la sangre capilar. El CO2 es más difusible que el O2 por su mayor solubilidad, y el intercambio es difusión simple, no facilitada.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Con respecto al transporte de gases en sangre:',
    options: [
      'La mayor parte del CO2 es transportado unido a la hemoglobina.',
      'La mayor parte del O2 es transportado en forma de ión bicarbonato.',
      'La hemoglobina tiene mayor afinidad por el monóxido de carbono (CO) que por el O2.',
    ],
    correctIndex: 2,
    explanation: 'La afinidad de la hemoglobina por el monóxido de carbono supera ampliamente a la que tiene por el oxígeno, lo que explica la toxicidad del CO. El CO2 viaja mayoritariamente como bicarbonato y el O2 unido a la hemoglobina, al revés de lo que plantean las otras opciones.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q41',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'La administración de acetilcolina tendrá el siguiente efecto a nivel cardíaco:',
    options: [
      'Aumento de la frecuencia cardíaca.',
      'Aumento del gasto cardíaco.',
      'Disminución del inotropismo.',
    ],
    correctIndex: 2,
    explanation: 'La acetilcolina actúa sobre receptores muscarínicos cardíacos reduciendo frecuencia, contractilidad y por lo tanto gasto. Las dos opciones restantes plantean aumentos, que corresponden al estímulo simpático.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q42',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'De acuerdo al control hemodinámico del flujo sanguíneo local, el mecanismo de autorregulación tiene como objetivo mantener constante:',
    options: [
      'La presión arterial.',
      'El flujo sanguíneo.',
      'La resistencia vascular.',
    ],
    correctIndex: 1,
    explanation: 'La autorregulación busca sostener el flujo local constante frente a variaciones de la presión de perfusión, ajustando para ello la resistencia. La presión arterial es la variable de entrada, no el objetivo, y la resistencia es el medio.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q43',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'En relación al flujo sanguíneo coronario a nivel del ventrículo izquierdo, es correcto afirmar que este es máximo durante:',
    options: [
      'La sístole.',
      'La diástole.',
      'La eyección ventricular.',
    ],
    correctIndex: 1,
    explanation: 'Durante la sístole la contracción del ventrículo izquierdo comprime sus vasos intramurales y frena el flujo, de modo que la perfusión ocurre sobre todo en diástole. La eyección ventricular es parte de la sístole, con el mismo problema.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación a la mecánica ventilatoria durante la inspiración:',
    options: [
      'La presión alveolar y la presión atmosférica son iguales.',
      'La presión alveolar es menor que la presión atmosférica.',
      'La presión alveolar es mayor que la presión atmosférica.',
    ],
    correctIndex: 1,
    explanation: 'La expansión torácica durante la inspiración hace caer la presión alveolar por debajo de la atmosférica, y ese gradiente es el que arrastra el aire hacia adentro. Presiones iguales corresponden a la ausencia de flujo y una presión alveolar mayor, a la espiración.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q46',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'En relación con los mecanismos involucrados en el control de la ventilación:',
    options: [
      'Los quimiorreceptores centrales responden preferentemente a los cambios en la concentración de protones.',
      'Los receptores “J” o yuxtacapilares responden enérgicamente frente a la aparición de sustancias irritantes.',
      'Los quimiorreceptores periféricos responden enérgicamente frente al estiramiento excesivo de la caja torácica.',
    ],
    correctIndex: 0,
    explanation: 'Los quimiorreceptores centrales del bulbo responden a los hidrogeniones del líquido cefalorraquídeo, generados a partir del CO2 que difunde desde la sangre. Los receptores J responden a la congestión y el estiramiento no es el estímulo de los quimiorreceptores periféricos.',
  },
  {
    id: 'CYR-PROTOTIPO-1-Q47',
    source: 'exam',
    exam: 'PROTOTIPO 1',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Con respecto a los grupos neuronales involucrados en la generación y el mantenimiento del ritmo respiratorio:',
    options: [
      'El grupo Neumotáxico estimula la inspiración.',
      'El grupo Apnéustico controla el punto de inactivación de la rampa inspiratoria.',
      'El grupo respiratorio dorsal es responsable de generar la señal en rampa inspiratoria.',
    ],
    correctIndex: 2,
    explanation: 'El grupo respiratorio dorsal genera la señal en rampa que produce la inspiración. El neumotáxico limita la inspiración en lugar de estimularla, y es él, y no el apnéustico, el que fija el punto de corte de la rampa.',
  },
  // ============== PROTOTIPO 2 ==============
  {
    id: 'CYR-PROTOTIPO-2-Q23',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto al electrocardiograma (ECG). Señale la opción correcta:',
    options: [
      'El intervalo QT se corresponde con la duración promedio del potencial de acción ventricular.',
      'Los intervalos del ECG constituyen segmentos isoeléctricos.',
      'La onda T representa la meseta del potencial de acción ventricular.',
    ],
    correctIndex: 0,
    explanation: 'El intervalo QT abarca desde el inicio de la despolarización ventricular hasta el fin de su repolarización, que es la duración del potencial de acción ventricular. Los intervalos incluyen ondas además de segmentos, y la onda T corresponde a la repolarización, no a la meseta.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q25',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Con respecto a la mecánica respiratoria:',
    options: [
      'La espirometría no permite determinar si existe obstrucción en el intercambio de aire entre los pulmones y la atmósfera.',
      'El volumen de reserva espiratoria no se puede medir con el espirómetro.',
      'Las capacidades pulmonares se definen como la suma de dos o más volúmenes pulmonares.',
    ],
    correctIndex: 2,
    explanation: 'Una capacidad pulmonar es, por definición, la suma de dos o más volúmenes. La espirometría sí detecta patrones obstructivos y el volumen de reserva espiratoria es perfectamente medible; lo que escapa al espirómetro es el volumen residual.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a las bases físicas de la hemodinamia, se puede afirmar que:',
    options: [
      'La viscosidad sanguínea es inversamente proporcional a la resistencia al flujo.',
      'La sangre se comporta como un líquido ideal.',
      'La resistencia viscosa de un lecho vascular se puede calcular como el cociente: Presión de perfusión / Gasto.',
    ],
    correctIndex: 2,
    explanation: 'Por analogía con la ley de Ohm, la resistencia de un lecho vascular es el cociente entre la presión de perfusión y el gasto. La sangre es un fluido real y no ideal, y su viscosidad es directamente proporcional a la resistencia.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q27',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a las bases físicas de la hemodinamia, indique la opción correcta.',
    options: [
      'Un líquido real es aquel que no presenta viscosidad.',
      'Para un tubo cilíndrico, la velocidad de circulación es inversamente proporcional a la superficie de sección.',
      'Si el radio de un vaso se reduce a la mitad, la resistencia al flujo se duplicará.',
    ],
    correctIndex: 1,
    explanation: 'Con caudal constante, la velocidad de circulación es inversamente proporcional a la sección del tubo. Un líquido real sí tiene viscosidad, y reducir el radio a la mitad multiplica la resistencia por dieciséis, no por dos.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q28',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Con respecto al potencial de acción cardiaco, es correcto afirmar que:',
    options: [
      'Las células ventriculares normalmente muestran despolarización diastólica espontánea.',
      'La rápida despolarización de las células ventriculares se debe a la entrada de Na+ a la célula.',
      'La entrada de Na+ durante la fase de meseta del potencial de acción es el mediador del acople excito- contráctil.',
    ],
    correctIndex: 1,
    explanation: 'La fase 0 del potencial de acción ventricular es una corriente rápida de entrada de sodio. La despolarización diastólica espontánea es propia de las células marcapasos, y el acople excitocontráctil lo media el calcio de la meseta, no el sodio.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q30',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a la perfusión de los órganos, marque la opción correcta:',
    options: [
      'El flujo de perfusión es inversamente proporcional al gasto cardíaco.',
      'El flujo de perfusión es inversamente proporcional a la resistencia vascular.',
      'El principal determinante de los cambios de resistencia al flujo se debe a cambios en la longitud de los capilares.',
    ],
    correctIndex: 1,
    explanation: 'A mayor resistencia vascular, menor flujo de perfusión para una misma presión. El flujo acompaña al gasto cardíaco en lugar de oponerse a él, y la resistencia se modifica sobre todo por cambios de radio, no de longitud.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q31',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Con respecto al flujo coronario capilar, marque la opción correcta:',
    options: [
      'Sus determinantes son la presión de perfusión, la resistencia vascular y las fuerzas compresivas extravasculares.',
      'La red capilar presenta una baja densidad similar al resto de los tejidos del cuerpo.',
      'Los esfínteres pre-capilares presentan un tono constante que mantiene la resistencia independiente de las necesidades metabólicas.',
    ],
    correctIndex: 0,
    explanation: 'El flujo coronario capilar depende de la presión de perfusión, de la resistencia vascular y de la compresión que el miocardio ejerce sobre sus propios vasos durante la sístole. La densidad capilar del corazón es alta, y los esfínteres precapilares ajustan su tono según la demanda metabólica.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: '¿Qué sucede con las presiones en el aparato respiratorio en estado de reposo (sin flujo aéreo)?',
    options: [
      'La presión alveolar es igual a la presión atmosférica.',
      'La presión pleural es igual a la presión atmosférica.',
      'La presión pleural es mayor que la presión atmosférica.',
    ],
    correctIndex: 0,
    explanation: 'Sin flujo aéreo la presión alveolar iguala a la atmosférica. La presión pleural, en cambio, se mantiene negativa incluso en reposo: es lo que impide que el pulmón colapse.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q35',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Durante el ejercicio físico intenso la disociación de la hemoglobina del O2 presenta la siguiente característica:',
    options: [
      'Disminuye la afinidad de la hemoglobina por el oxígeno.',
      'La curva de disociación se desplaza hacia la izquierda.',
      'La P50 disminuye.',
    ],
    correctIndex: 0,
    explanation: 'El ejercicio genera acidosis, hipercapnia y aumento de temperatura, que desplazan la curva hacia la derecha y reducen la afinidad, facilitando la entrega de oxígeno al músculo. Ese desplazamiento eleva la P50 en lugar de reducirla.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q36',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a la presión arterial, marque la opción correcta:',
    options: [
      'El volumen de eyección sistólica está inversamente relacionado con la presión arterial.',
      'La distensibilidad aórtica permite la continuidad del flujo sanguíneo durante la diástole.',
      'A mayor radio de las arteriolas, mayor será la presión arterial.',
    ],
    correctIndex: 1,
    explanation: 'La aorta se distiende en sístole y devuelve ese volumen en diástole, sosteniendo el flujo cuando el ventrículo ya no eyecta. Un mayor radio arteriolar reduce la resistencia y por lo tanto la presión, y el volumen sistólico se relaciona con la presión en forma directa.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q37',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: '¿Cuál de estos eventos describe mejor los mecanismos que se ponen en marcha para compensar la presión arterial frente a una hemorragia severa?',
    options: [
      'Aumenta la descarga de los barorreceptores, lo que activa el centro vasodilatador, aumentando así la actividad parasimpática y con el consiguiente aumento de la presión arterial.',
      'Aumenta la actividad simpática por disminución de la actividad de los barorreceptores, con un incremento de la resistencia periférica y la frecuencia cardíaca.',
      'Aumenta la actividad parasimpática, lo que genera un aumento en la frecuencia cardíaca.',
    ],
    correctIndex: 1,
    explanation: 'La caída de la presión reduce la descarga de los barorreceptores, lo que desinhibe el centro vasomotor y aumenta la actividad simpática: sube la resistencia periférica y la frecuencia cardíaca. Las otras dos opciones invocan una respuesta parasimpática, que bajaría aún más la presión.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Si una persona quiere inflar un globo, necesita obtener mayor volumen de aire. En dicha situación se activarán:',
    options: [
      'Únicamente las neuronas respiratorias del grupo dorsal',
      'Únicamente las neuronas respiratorias del grupo ventral',
      'Se activarán las neuronas del grupo dorsal y ventral',
    ],
    correctIndex: 2,
    explanation: 'Una inspiración profunda requiere reclutar el grupo ventral además del dorsal, que es el que basta para la respiración tranquila. Ninguno de los dos actúa en forma exclusiva en esta situación.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q40',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'Las arterias elásticas poseen: (Indique lo correcto)',
    options: [
      'Un endotelio cúbico simple.',
      'Una limitante elástica interna más evidente que la de las arterias musculares.',
      'Láminas elásticas en su capa media',
    ],
    correctIndex: 2,
    explanation: 'La túnica media de la arteria elástica está formada por láminas elásticas concéntricas alternadas con músculo liso. Su endotelio es plano y su limitante elástica interna queda disimulada entre esas láminas, a diferencia de la arteria muscular.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q42',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Una de las características estructurales de las células del músculo cardiaco específico o de conducción es:',
    options: [
      'Células de gran tamaño en comparación con las del miocardio de contracción',
      'Células con escaso glucógeno en su citoplasma',
      'Células con gran cantidad de miofibrillas en su citoplasma',
    ],
    correctIndex: 0,
    explanation: 'Las células de conducción son de mayor tamaño que las contráctiles, con abundante glucógeno y escasas miofibrillas desplazadas hacia la periferia. Las otras dos opciones invierten justamente esos rasgos.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q43',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Los capilares de tipo continuo se encuentran en (Indique lo correcto):',
    options: [
      'Pulpa roja del bazo',
      'Glomérulos renales',
      'Intersticio alveolar',
    ],
    correctIndex: 2,
    explanation: 'El capilar del intersticio alveolar es de tipo continuo, condición necesaria para la barrera hematogaseosa. La pulpa roja esplénica tiene sinusoides y el glomérulo renal, capilares fenestrados.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q44',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿A qué tipo de epitelio de las vías aéreas corresponde la siguiente descripción al microscopio óptico? Epitelio seudoestratificado alto formado por tres tipos celulares: Células de sostén cilíndricas altas con numerosas microvellosidades en la superficie apical. Neuronas bipolares cuyo axón atraviesa la lámina basal y se introduce en el conjuntivo subyacente. Células basales pequeñas que no alcanzan la superficie apical del epitelio:',
    options: [
      'Epitelio Olfatorio',
      'Epitelio Respiratorio',
      'Epitelio Alveolar',
    ],
    correctIndex: 0,
    explanation: 'La presencia de neuronas bipolares dentro del epitelio, con su axón atravesando la lámina basal, es exclusiva del epitelio olfatorio. El respiratorio es ciliado con células caliciformes y el alveolar es plano simple.',
  },
  {
    id: 'CYR-PROTOTIPO-2-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 2',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'Los bronquiolos propiamente dichos presentan: (Indique lo correcto)',
    options: [
      'Placas de cartílago en su pared.',
      'Una capa continua de músculo liso en su pared.',
      'Alvéolos en su pared',
    ],
    correctIndex: 1,
    explanation: 'El bronquiolo propiamente dicho ya perdió el cartílago y presenta una capa continua de músculo liso, responsable de la broncoconstricción. Los alvéolos en la pared aparecen recién en el bronquiolo respiratorio.',
  },
  // ============== PROTOTIPO 3 ==============
  {
    id: 'CYR-PROTOTIPO-3-Q25',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿Cuál de las siguientes estructuras del aparato respiratorio están tapizadas por un epitelio seudoestratificado denominado epitelio respiratorio?',
    options: [
      'Bronquios',
      'Bronquiolos terminales',
      'Alveolos',
    ],
    correctIndex: 0,
    explanation: 'Los bronquios conservan el epitelio seudoestratificado cilíndrico ciliado con caliciformes. En los bronquiolos terminales el epitelio ya es simple, y el alvéolo está tapizado por neumocitos planos.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'En el epitelio respiratorio, las células cilíndricas presentan en su borde apical las siguientes estructuras:',
    options: [
      'Cilias',
      'Estereocilios',
      'Microvellosidades',
    ],
    correctIndex: 0,
    explanation: 'Las células cilíndricas del epitelio respiratorio son ciliadas, y ese batido es el que moviliza el moco. Los estereocilios corresponden al epidídimo y las microvellosidades al intestino.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q27',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿Cuáles son los elementos que integran la barrera hematogaseosa?',
    options: [
      'Endotelio de capilar continuo, lámina basal endotelial, lámina basal epitelial y Neumocito tipo I',
      'Endotelio de capilar fenestrado, lámina basal endotelial, lámina basal epitelial y Neumocito tipo II',
      'Endotelio de capilar y lámina basal discontinua, y Neumocito tipo II',
    ],
    correctIndex: 0,
    explanation: 'La barrera hematogaseosa está formada por el endotelio del capilar continuo, ambas láminas basales fusionadas y el neumocito tipo I, que es el que cubre la mayor parte de la superficie alveolar. El neumocito tipo II secreta surfactante pero no participa del intercambio.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q29',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿En qué se diferencia una arteria muscular de una elástica?',
    options: [
      'La arteria muscular carece de lámina elástica interna',
      'La arteria muscular posee un diámetro mayor que la arteria elástica',
      'La túnica media de la arteria muscular posee múltiples capas de células musculares lisas concéntricas con poco material elástico',
    ],
    correctIndex: 2,
    explanation: 'La diferencia está en la túnica media: en la arteria muscular predominan capas concéntricas de músculo liso con poco material elástico. La lámina elástica interna está presente y es más notoria que en la elástica, y su diámetro es menor.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q30',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Cómo será el cambio en la presión arterial si la frecuencia cardíaca se ve incrementada y el volumen sistólico disminuye en forma proporcional, sin cambios en la resistencia periférica:',
    options: [
      'Se incrementa',
      'Disminuye',
      'No se observan cambios.',
    ],
    correctIndex: 2,
    explanation: 'El gasto cardíaco es el producto de frecuencia por volumen sistólico, de modo que si uno sube y el otro baja en la misma proporción, el gasto no cambia. Con resistencia periférica constante, la presión arterial media tampoco se modifica.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q31',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Un sujeto con una proporción elevada de colágeno en sus arterias, en comparación con un individuo promedio, presentará:',
    options: [
      'menor flujo sanguíneo arterial durante diástole',
      'flujo sanguíneo constante a nivel capilar',
      'mayor distensibilidad arterial',
    ],
    correctIndex: 0,
    explanation: 'Más colágeno significa una arteria menos distensible, incapaz de devolver en diástole el volumen almacenado en sístole. El flujo capilar se vuelve entonces más pulsátil y cae durante la diástole.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'En relación al transporte de gases en sangre:',
    options: [
      'Cuando el contenido de CO2 de la sangre aumenta, la curva de disociación de la hemoglobina por el O2 se desplaza a la derecha.',
      'El efecto Haldane determina que la presión parcial de O2 incrementa la afinidad de la hemoglobina por el CO2.',
      'El efecto Bohr determina que la presión parcial de O2 incrementa la afinidad de la hemoglobina por el CO2.',
    ],
    correctIndex: 0,
    explanation: 'El aumento del CO2 acidifica la sangre y desplaza la curva de disociación hacia la derecha, favoreciendo la entrega de oxígeno en los tejidos. Es el efecto Bohr; el Haldane describe cómo la oxigenación reduce la afinidad por el CO2, no la aumenta.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q33',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'En condiciones normales, la distribución de flujo sanguíneo y ventilación pulmonar en un sujeto de pie presenta una de las siguientes características:',
    options: [
      'El flujo sanguíneo es mayor en el vértice que en la base del pulmón.',
      'La relación ventilación/perfusión (V/Q) es mayor en el vértice que en la base del pulmón.',
      'La ventilación alveolar se incrementa en forma más pronunciada que el flujo sanguíneo desde el vértice hacia la base del pulmón.',
    ],
    correctIndex: 1,
    explanation: 'En bipedestación la gravedad reduce tanto la ventilación como la perfusión hacia el vértice, pero la perfusión cae mucho más, de modo que el cociente V/Q es mayor arriba. El flujo sanguíneo, por lo tanto, es máximo en la base.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q36',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'En relación a los mecanismos de control del flujo sanguíneo local por autorregulación, es correcto afirmar que:',
    options: [
      'Induce cambios en la presión sanguínea para ajustar el flujo sanguíneo',
      'Implica mantener el flujo sanguíneo constante frente a cambios de la presión arterial',
      'Implica cambios en la resistencia vascular para mantener la presión sanguínea constante',
    ],
    correctIndex: 1,
    explanation: 'La autorregulación sostiene el flujo local constante cuando la presión de perfusión varía, ajustando el calibre de las arteriolas. No modifica la presión sistémica ni tiene a la presión como objetivo.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q37',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'De acuerdo al control metabólico, el flujo sanguíneo local aumenta en respuesta a:',
    options: [
      'aumento del O2 disponible',
      'aumento de la producción de CO2',
      'disminución de la producción de CO2',
    ],
    correctIndex: 1,
    explanation: 'El CO2 acumulado por el metabolismo activo es una señal vasodilatadora local que aumenta el flujo hacia el tejido que lo produce. Un exceso de oxígeno disponible o una menor producción de CO2 tienen el efecto contrario.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q38',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación al surfactante pulmonar:',
    options: [
      'Su efecto varía en forma inversa al área en la cual está distribuido',
      'Aumenta la tensión superficial en la interfase aire-líquido del alvéolo',
      'La ausencia de surfactante evita el colapso de los alvéolos de menor radio',
    ],
    correctIndex: 0,
    explanation: 'El surfactante se concentra cuando el alvéolo se achica y se dispersa cuando se expande, de modo que su efecto es mayor a menor área: eso estabiliza los alvéolos pequeños. Su función es reducir la tensión superficial, y sin él los alvéolos de menor radio son justamente los que colapsan.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación a la mecánica ventilatoria:',
    options: [
      'La inspiración en reposo es un proceso pasivo.',
      'Los músculos inspiratorios accesorios contribuyen a los movimientos ventilatorios durante el ejercicio.',
      'La contracción del diafragma disminuye el volumen torácico, y el aire es expulsado fuera de los pulmones.',
    ],
    correctIndex: 1,
    explanation: 'Los músculos inspiratorios accesorios, como los escalenos y el esternocleidomastoideo, se reclutan cuando aumenta la demanda ventilatoria. La inspiración en reposo es activa, y la contracción del diafragma aumenta el volumen torácico en lugar de reducirlo.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q40',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'En cuanto al control central de la respiración:',
    options: [
      'Las neuronas del grupo respiratorio dorsal del tronco encefálico presentan una señal en rampa inspiratoria.',
      'El grupo respiratorio apnéustico del hipotálamo lateral controla el punto de inactivación de la rampa inspiratoria.',
      'El grupo neumotáxico de la médula espinal estimula la inspiración aumentando la duración de la rampa inspiratoria.',
    ],
    correctIndex: 0,
    explanation: 'El grupo respiratorio dorsal genera la señal en rampa que produce la inspiración. Las otras dos opciones ubican mal los centros: el apnéustico y el neumotáxico están en la protuberancia, no en el hipotálamo ni en la médula espinal, y el neumotáxico limita la inspiración en vez de prolongarla.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q41',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Con respecto al control central de la respiración:',
    options: [
      'Los quimiorreceptores centrales responden preferentemente a los cambios en la presión parcial de O2.',
      'Los quimiorreceptores del callado aórtico y los senos carotídeos se activan frente al descenso del pH y la pO2 así como al aumento de la pCO2.',
      'Los receptores de estiramiento pulmonar responden a la presencia de gases nocivos, humo de cigarrillo, aire frío y polvillos inhalados.',
    ],
    correctIndex: 1,
    explanation: 'Los quimiorreceptores periféricos del cayado aórtico y los senos carotídeos responden a la caída del pH y de la pO2 y al aumento de la pCO2. Los centrales responden a los hidrogeniones y no a la pO2, y los receptores irritantes, no los de estiramiento, detectan gases nocivos y aire frío.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q42',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto a la actividad eléctrica de una fibra miocárdica:',
    options: [
      'Cuando toda la fibra está despolarizada se registra una diferencia de potencial eléctrico extracelular positivo.',
      'Cuando toda la fibra está repolarizada se registra una diferencia de potencial eléctrico extracelular positivo.',
      'Los procesos de despolarización y repolarización, que ocurren en una fibra miocárdica, se pueden modelar con un dipolo elemental.',
    ],
    correctIndex: 2,
    explanation: 'El frente de despolarización que recorre la fibra separa una zona positiva de una negativa y se modela como un dipolo elemental. Cuando la fibra está uniformemente despolarizada o repolarizada no hay separación de cargas y el registro extracelular es isoeléctrico.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q43',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'El momento dipolar instantáneo (Mi) es un vector que representa la actividad eléctrica cardíaca para cada instante de tiempo. ¿Cuál de las siguientes opciones es correcta?',
    options: [
      'El Mi posee unidades de voltios (V).',
      'El Mi posee unidades de coulomb por metros (C·m).',
      'La proyección del Mi sobre la recta de derivación L es igual a la derivación unipolar aumentada L (aVL)',
    ],
    correctIndex: 1,
    explanation: 'El momento dipolar es el producto de la carga por la distancia que separa las cargas, de modo que sus unidades son coulomb por metro. Los voltios corresponden al potencial, y la proyección sobre una recta de derivación da la derivación bipolar correspondiente.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q44',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a los regímenes de circulación:',
    options: [
      'El cambio de régimen laminar a turbulento es un fenómeno irreversible.',
      'En el sistema circulatorio el flujo normal es turbulento en la mayor parte de los sectores.',
      'Cuando la velocidad de circulación es menor a la velocidad crítica, el régimen es laminar.',
    ],
    correctIndex: 2,
    explanation: 'El régimen se mantiene laminar mientras la velocidad esté por debajo de la crítica y vuelve a serlo si la velocidad desciende: el cambio es reversible. En condiciones normales la circulación es laminar en casi todo el árbol vascular.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a la ley de Poiseuille:',
    options: [
      'Establece una relación lineal entre el gasto y la variación de presión entre los extremos de un tubo por el que circula un líquido no newtoniano.',
      'El gasto es directamente proporcional a la resistencia viscosa.',
      'No es aplicable al régimen turbulento.',
    ],
    correctIndex: 2,
    explanation: 'La ley de Poiseuille describe el flujo de un líquido newtoniano en régimen laminar, de modo que deja de valer cuando el flujo se vuelve turbulento. El gasto es inversamente proporcional a la resistencia, y la relación lineal entre gasto y diferencia de presión solo se sostiene en régimen laminar.',
  },
  {
    id: 'CYR-PROTOTIPO-3-Q46',
    source: 'exam',
    exam: 'PROTOTIPO 3',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Con respecto a las presiones en el aparato respiratorio:',
    options: [
      'La presión transmural del pulmón es igual a la diferencia de presión entre la pleura y la atmósfera.',
      'Durante la inspiración, la presión alveolar cae por debajo de la presión atmosférica.',
      'Durante la inspiración, la presión pleural supera la presión atmosférica.',
    ],
    correctIndex: 1,
    explanation: 'La expansión torácica hace caer la presión alveolar por debajo de la atmosférica y ese gradiente genera el flujo inspiratorio. La presión pleural se vuelve aún más negativa durante la inspiración, y la transmural pulmonar es la diferencia entre alvéolo y pleura.',
  },
  // ============== PROTOTIPO 4 ==============
  {
    id: 'CYR-PROTOTIPO-4-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿Qué tipo celular forma la capa media de las arteriolas?',
    options: [
      'Pericitos',
      'Fibroblastos',
      'Fibras musculares lisas',
    ],
    correctIndex: 2,
    explanation: 'La túnica media de la arteriola está formada por fibras musculares lisas, cuyo tono regula la resistencia periférica. Los pericitos acompañan a los capilares y los fibroblastos pertenecen al tejido conjuntivo.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q27',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: '¿Qué tipo de capilares se encuentran en el pulmón? Indique la opción correcta',
    options: [
      'Continuos',
      'Fenestrados',
      'Sinusoides',
    ],
    correctIndex: 0,
    explanation: 'El capilar pulmonar es continuo, condición necesaria para que la barrera hematogaseosa sea selectiva. Los fenestrados corresponden al glomérulo y a las glándulas endocrinas, y los sinusoides al hígado y al bazo.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q28',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: '¿Cuál capa del corazón tiene un componente mesotelial?',
    options: [
      'El endocardio',
      'El miocardio',
      'El epicardio',
    ],
    correctIndex: 2,
    explanation: 'El epicardio es la hoja visceral del pericardio seroso y por eso está revestido por mesotelio. El endocardio está tapizado por endotelio y el miocardio es músculo cardíaco.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q29',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿En cuál sector del aparato respiratorio se encuentran las células de Clara formando parte de su revestimiento epitelial?',
    options: [
      'En la tráquea',
      'En los bronquios',
      'En los bronquiolos',
    ],
    correctIndex: 2,
    explanation: 'Las células de Clara pertenecen al epitelio bronquiolar, donde reemplazan a las caliciformes. En tráquea y bronquios el epitelio sigue siendo respiratorio ciliado con células caliciformes.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q30',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Sobre los macrófagos alveolares, indique la opción correcta:',
    options: [
      'Se encuentran en la luz de los alvéolos',
      'Forman uniones con los neumonocitos I',
      'Forman el surfactante pulmonar',
    ],
    correctIndex: 0,
    explanation: 'El macrófago alveolar reside en la luz del alvéolo, donde fagocita partículas que llegaron con el aire. El surfactante lo produce el neumocito tipo II y estos macrófagos no forman uniones estables con el epitelio.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'En una situación donde la entrada de aire hacia un alvéolo pulmonar se obstruye y el flujo sanguíneo no se modifica, el aire contenido en el alvéolo podría presentar los siguientes valores de presiones parciales (medidos en mm Hg):',
    options: [
      'PO2 = 40, PCO2 = 46',
      'PO2 = 40, PCO2 = 0',
      'PO2 = 0, PCO2 = 40',
    ],
    correctIndex: 0,
    explanation: 'Si el alvéolo queda sin ventilación pero conserva perfusión, su gas se equilibra con el de la sangre venosa mixta: PO2 cercana a 40 y PCO2 cercana a 46 mmHg. Es la situación de cortocircuito, con relación ventilación/perfusión igual a cero.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q33',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación a la mecánica ventilatoria es correcto afirmar que:',
    options: [
      'La espiración en reposo (no forzada) constituye un proceso activo',
      'La inspiración en reposo (no forzada) constituye un proceso activo',
      'La inspiración en reposo (no forzada) depende fundamentalmente de la contracción de los músculos intercostales externos.',
    ],
    correctIndex: 1,
    explanation: 'La inspiración en reposo requiere la contracción del diafragma, de modo que es un proceso activo, mientras que la espiración tranquila es pasiva por retroceso elástico. El diafragma, y no los intercostales externos, es el principal responsable.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q35',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Si una persona realiza una hiperventilación voluntaria, ¿qué ocurre con el pH a nivel arterial?',
    options: [
      'Aumenta.',
      'Disminuye.',
      'No se modifica.',
    ],
    correctIndex: 0,
    explanation: 'La hiperventilación elimina CO2 más rápido de lo que se produce, baja la PCO2 arterial y con ella la concentración de hidrogeniones: el pH sube. Es una alcalosis respiratoria.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q36',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Sobre los centros que controlan la respiración a nivel central, marque la opción correcta:',
    options: [
      'El centro apnéustico estimula sobre todo la espiración forzada.',
      'El centro neumotáxico controla el punto de inactivación de la rampa inspiratoria.',
      'El grupo ventral bulbar es el que actúa constantemente para mantener la respiración tranquila.',
    ],
    correctIndex: 1,
    explanation: 'El centro neumotáxico interrumpe la rampa inspiratoria y así determina la duración de la inspiración. El apnéustico prolonga la inspiración en lugar de estimular la espiración, y la respiración tranquila la sostiene el grupo dorsal.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q37',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Con respecto a las presiones en el sistema circulatorio, marque la opción correcta:',
    options: [
      'La presión en el extremo arterial de los capilares es mayor que a nivel arteriolar.',
      'La presión en los capilares es pulsátil.',
      'La presión en las venas y vénulas no es pulsátil.',
    ],
    correctIndex: 2,
    explanation: 'El pulso se amortigua al atravesar las arteriolas, de modo que en venas y vénulas la presión ya no es pulsátil. En el extremo arterial del capilar la presión es menor que en la arteriola, no mayor.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q38',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Sobre las acciones de la Angiotensina II es correcto afirmar que:',
    options: [
      'Produce vasodilatación.',
      'Inhibe la secreción de la hormona antidiurética.',
      'Estimula el sistema nervioso simpático.',
    ],
    correctIndex: 2,
    explanation: 'La angiotensina II potencia la descarga simpática, además de ser un vasoconstrictor directo y de estimular la liberación de hormona antidiurética y aldosterona. Las otras dos opciones invierten sus efectos.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'De acuerdo al control hemodinámico local del flujo sanguíneo, el mecanismo de autorregulación tiene como objetivo:',
    options: [
      'Aumentar el flujo sanguíneo frente a incrementos de la presión arterial.',
      'Disminuir el flujo sanguíneo frente a una disminución de la presión arterial.',
      'Mantener el flujo sanguíneo constante frente a cambios de la presión arterial.',
    ],
    correctIndex: 2,
    explanation: 'El objetivo de la autorregulación es mantener el flujo constante pese a las variaciones de la presión arterial, ajustando la resistencia local. Las otras dos opciones describen justamente lo que la autorregulación evita.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q40',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'En relación a la circulación coronaria, es correcto afirmar que el aporte de oxígeno es:',
    options: [
      'máximo durante la sístole.',
      'máximo durante la diástole.',
      'igual en sístole y en diástole.',
    ],
    correctIndex: 1,
    explanation: 'Durante la sístole el miocardio comprime sus vasos intramurales, de modo que el aporte de oxígeno al ventrículo izquierdo ocurre principalmente en diástole. Por eso una taquicardia sostenida, que acorta la diástole, compromete la perfusión coronaria.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q43',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a la presión arterial (PA), es correcto afirmar que:',
    options: [
      'La PA media se calcula como la diferencia entre la presión sistólica y la presión diastólica.',
      'Está determinada por la resistencia vascular periférica y el gasto cardíaco.',
      'A mayor radio en el vaso, mayor será la PA.',
    ],
    correctIndex: 1,
    explanation: 'La presión arterial media es el producto del gasto cardíaco por la resistencia vascular periférica. La diferencia entre sistólica y diastólica es la presión diferencial, y un mayor radio del vaso reduce la resistencia y con ella la presión.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q44',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto al control de la presión arterial (PA), es correcto afirmar que:',
    options: [
      'Su principal centro regulador está localizado en el hipotálamo.',
      'La administración de un bloqueante de los receptores adrenérgicos provoca un incremento de la PA.',
      'La activación del sistema renina-angiotensina-aldosterona provoca un incremento en la PA.',
    ],
    correctIndex: 2,
    explanation: 'El sistema renina-angiotensina-aldosterona eleva la presión por vasoconstricción y retención de sodio y agua. El centro regulador principal está en el bulbo y no en el hipotálamo, y bloquear los receptores adrenérgicos baja la presión en lugar de subirla.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a la cinética de la circulación sanguínea, marque la opción correcta:',
    options: [
      'El flujo o gasto se calcula como sección por longitud.',
      'Las leyes que rigen el movimiento estacionario de los líquidos no son aplicables a la circulación sanguínea.',
      'La velocidad media de circulación se define como el cociente entre la longitud que recorre el líquido y el tiempo que tarda en hacerlo.',
    ],
    correctIndex: 2,
    explanation: 'La velocidad media es el cociente entre la distancia recorrida y el tiempo empleado. El gasto es sección por velocidad, no por longitud, y las leyes del movimiento estacionario sí se aplican a la circulación como aproximación.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q46',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Dado un sistema formado por un tubo recto, por el que circula un líquido, marque la opción correcta:',
    options: [
      'Un líquido newtoniano posee viscosidad constante.',
      'El cambio entre régimen laminar a turbulento y viceversa, es un fenómeno irreversible.',
      'Cuando un líquido ideal circula con régimen laminar a lo largo de un tubo de paredes rígidas aparecen fuerzas cohesivas (fuerza de rozamiento) entre las capas contiguas.',
    ],
    correctIndex: 0,
    explanation: 'Un líquido newtoniano mantiene su viscosidad constante, independiente del cizallamiento; la sangre no lo es. El paso de laminar a turbulento es reversible, y un líquido ideal carece por definición de fuerzas de rozamiento internas.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q47',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Sobre las leyes de los gases, marque la opción correcta:',
    options: [
      'A igual temperatura y presión, un mol de CO2 ocupa mayor volumen que un mol de O2.',
      'La ley de Henry establece que la velocidad de difusión de un gas depende de la masa molar de ese gas.',
      'La presión parcial de un gas en una mezcla es la presión que tendría dicho gas, si a igual temperatura se encontrara solo, ocupando todo el volumen.',
    ],
    correctIndex: 2,
    explanation: 'La presión parcial es la que ejercería un gas si ocupara solo todo el volumen de la mezcla, a la misma temperatura. Un mol de cualquier gas ocupa el mismo volumen en iguales condiciones, y la relación entre difusión y masa molar corresponde a la ley de Graham, no a la de Henry.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q48',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Con respecto a las bases físicas de la función respiratoria, señale la opción correcta:',
    options: [
      'La contracción de los músculos de la pared abdominal favorece la espiración tranquila.',
      'Tanto en una respiración tranquila como forzada, la inspiración es activa.',
      'La capacidad pulmonar total es igual a la suma del volumen de reserva inspiratoria más el volumen de reserva espiratoria.',
    ],
    correctIndex: 1,
    explanation: 'La inspiración siempre requiere contracción muscular, tanto en reposo como en esfuerzo. La musculatura abdominal participa en la espiración forzada, no en la tranquila, y la capacidad pulmonar total incluye además el volumen corriente y el residual.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q49',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto al potencial en un punto P (VP) del campo eléctrico generado por un dipolo, marque la opción correcta:',
    options: [
      'La relación entre el VP y el inverso del cuadrado de la distancia entre centro del dipolo y el punto P (1/r²) es lineal.',
      'El VP depende de una constante adimensional, que involucra la naturaleza del medio en el que se encuentra el dipolo (K).',
      'El VP es independiente de la distancia que separa ambas cargas.',
    ],
    correctIndex: 0,
    explanation: 'El potencial generado por un dipolo decae con el inverso del cuadrado de la distancia, de modo que la relación con esa magnitud es lineal. La constante del medio no es adimensional y el potencial sí depende de la separación entre las cargas.',
  },
  {
    id: 'CYR-PROTOTIPO-4-Q50',
    source: 'exam',
    exam: 'PROTOTIPO 4',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto a los procesos eléctricos que ocurren en el miocardio, marque la opción correcta:',
    options: [
      'El electrocardiograma y el potencial de acción no se correlacionan.',
      'El momento dipolar instantáneo se calcula como la suma algebraica de los momentos dipolares elementales.',
      'Tanto el momento dipolar instantáneo como el eje eléctrico instantáneo constituyen una imagen representativa de la actividad eléctrica cardíaca para cada instante de tiempo.',
    ],
    correctIndex: 2,
    explanation: 'Tanto el momento dipolar instantáneo como el eje eléctrico instantáneo representan la actividad eléctrica del corazón en cada momento. La suma de los momentos elementales es vectorial y no algebraica, y el electrocardiograma se correlaciona estrechamente con los potenciales de acción.',
  },
  // ============== PROTOTIPO 5 ==============
  {
    id: 'CYR-PROTOTIPO-5-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'Las arterias musculares se caracterizan porque poseen: (Indique lo correcto)',
    options: [
      'Un endotelio cúbico simple.',
      'Un diámetro mayor que las de las arterias elásticas.',
      'Una limitante elástica interna más evidente que la de las arterias elásticas.',
    ],
    correctIndex: 2,
    explanation: 'La limitante elástica interna es una lámina gruesa y bien definida en la arteria muscular, mientras que en la elástica queda enmascarada por las láminas de la media. El endotelio es plano y el calibre de las arterias elásticas es mayor.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q28',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Los capilares de tipo fenestrados se encuentran en:',
    options: [
      'Sistema nervioso central.',
      'Los glomérulos renales.',
      'El intersticio alveolar.',
    ],
    correctIndex: 1,
    explanation: 'El glomérulo renal tiene capilares fenestrados, adecuados para la filtración. El sistema nervioso central posee capilares continuos con uniones estrechas que forman la barrera hematoencefálica, y el intersticio alveolar también es continuo.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q29',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: '¿Qué componente del citoesqueleto produce el movimiento de las células ciliadas del revestimiento de la tráquea?',
    options: [
      'Microtúbulos.',
      'Microfilamentos.',
      'Filamentos intermedios.',
    ],
    correctIndex: 0,
    explanation: 'El batido ciliar depende del axonema, un arreglo de microtúbulos que se deslizan entre sí por acción de la dineína. Los microfilamentos y los filamentos intermedios cumplen funciones de motilidad y sostén distintas.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q30',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: 'Los bronquiolos respiratorios presentan: (Indique lo correcto)',
    options: [
      'Una capa continua de músculo liso en su pared.',
      'Placas de cartílago en su pared.',
      'Alvéolos en su pared.',
    ],
    correctIndex: 2,
    explanation: 'El bronquiolo respiratorio ya presenta alvéolos abriéndose en su pared, y por eso pertenece a la porción respiratoria del pulmón. El cartílago desapareció desde el bronquiolo y la capa muscular continua es propia del bronquiolo propiamente dicho.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q31',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'En una situación donde el flujo sanguíneo de un alvéolo pulmonar se ve interrumpido, el aire contenido en el mismo tendrá los siguientes valores de presiones parciales (medidos en mm Hg):',
    options: [
      'PO2 = 40, PCO2 = 46.',
      'PO2 = 40, PCO2 = 0.',
      'PO2 = 150, PCO2 = 0.',
    ],
    correctIndex: 2,
    explanation: 'Si el alvéolo conserva ventilación pero pierde perfusión, su gas se parece al aire inspirado humidificado: PO2 alta y PCO2 prácticamente nula. Es la situación de espacio muerto, opuesta al cortocircuito.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: '¿Cuál de las siguientes situaciones se corresponde con el efecto Bohr?',
    options: [
      'Un aumento en la concentración de CO2 incrementa la afinidad de la hemoglobina (Hb) por el O2.',
      'Un incremento en la concentración de CO2 desviará la curva de disociación de la Hb por el O2 hacia la derecha.',
      'Un incremento en la concentración de O2 desviará la curva de disociación de la Hb por el CO2 hacia la derecha.',
    ],
    correctIndex: 1,
    explanation: 'El efecto Bohr describe cómo el aumento de CO2 y de hidrogeniones desplaza la curva de disociación hacia la derecha, reduciendo la afinidad y liberando oxígeno donde el metabolismo lo demanda. El efecto del oxígeno sobre la afinidad por el CO2 es el efecto Haldane.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q33',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación a los volúmenes y capacidades pulmonares, es correcto afirmar que:',
    options: [
      'La capacidad residual funcional (CRF) corresponde a la suma del volumen residual (VR) y del volumen de reserva espiratoria (VRE).',
      'La capacidad pulmonar total (CPT) corresponde a la suma de la capacidad inspiratoria (CI) y el volumen residual (VR).',
      'El volumen residual (VR) puede ser medido de forma directa por espirometría simple.',
    ],
    correctIndex: 0,
    explanation: 'La capacidad residual funcional es el aire que queda tras una espiración tranquila y equivale al volumen residual más el de reserva espiratoria. La capacidad pulmonar total suma además el volumen corriente, y el residual no se mide por espirometría simple.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q34',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Con respecto a las funciones del surfactante pulmonar, es correcto afirmar que:',
    options: [
      'Determina una reducción de la distensibilidad (o compliance) pulmonar.',
      'Determina una relación lineal entre el radio alveolar y la tensión superficial del alvéolo.',
      'Previene el colapso alveolar provocado por el vaciado de los alvéolos de menor radio en los de mayor radio.',
    ],
    correctIndex: 2,
    explanation: 'Al reducir la tensión superficial más intensamente en los alvéolos pequeños, el surfactante iguala las presiones de colapso y evita que los alvéolos chicos se vacíen dentro de los grandes. Aumenta la distensibilidad y la relación entre radio y tensión no es lineal.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q35',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Sobre los quimiorreceptores que participan en el control central de la ventilación, marque la opción correcta:',
    options: [
      'Los receptores J (yuxtacapilares) están activos en la respiración normal.',
      'El principal estímulo de los receptores centrales es la caída de la presión de oxígeno.',
      'Los quimiorreceptores del cayado aórtico responden tanto a la disminución de la presión de oxígeno como del pH.',
    ],
    correctIndex: 2,
    explanation: 'Los cuerpos aórticos son quimiorreceptores periféricos que responden tanto a la caída de la presión de oxígeno como al descenso del pH. Los receptores centrales responden a los hidrogeniones y no a la hipoxia, y los receptores J se activan en la congestión, no en la respiración normal.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'El principal efecto de la autorregulación del flujo sanguíneo es ajustar:',
    options: [
      'La presión arterial frente a cambios en la resistencia vascular.',
      'La resistencia vascular frente a cambios en la presión arterial.',
      'La presión arterial frente a cambios en los requerimientos metabólicos.',
    ],
    correctIndex: 1,
    explanation: 'La autorregulación ajusta la resistencia vascular local cuando cambia la presión arterial, y así mantiene el flujo estable. La presión sistémica no es la variable que este mecanismo controla.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q40',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'En relación al control del flujo y de la resistencia vascular, señale la opción correcta:',
    options: [
      'La adenosina es un potente vasodilatador.',
      'El óxido nítrico es un potente vasoconstrictor.',
      'La acetilcolina es un potente vasoconstrictor.',
    ],
    correctIndex: 0,
    explanation: 'La adenosina es un vasodilatador potente y una de las principales señales metabólicas locales. El óxido nítrico y la acetilcolina también son vasodilatadores, de modo que las otras dos opciones invierten su efecto.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q42',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: '¿Cuál de las siguientes sustancias al unirse a los receptores de las células marcapasos del nodo sinusal hiperpolariza su potencial de membrana?',
    options: [
      'Noradrenalina.',
      'Acetilcolina.',
      'Adrenalina.',
    ],
    correctIndex: 1,
    explanation: 'La acetilcolina abre canales de potasio en las células marcapasos, hiperpolariza su membrana y enlentece la despolarización diastólica, bajando la frecuencia. La noradrenalina y la adrenalina producen el efecto contrario.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Con respecto a las leyes que rigen el movimiento estacionario de los líquidos, marque la opción correcta:',
    options: [
      'A lo largo de un tubo con secciones variables, en el sector del tubo con mayor sección la velocidad media de desplazamiento es mayor que la del sector con menor sección.',
      'Si el gasto es constante, este se puede calcular como el cociente entre la variación de volumen (ΔV) y la variación del tiempo (Δt).',
      'La circulación sanguínea constituye un fenómeno estacionario.',
    ],
    correctIndex: 1,
    explanation: 'Con gasto constante, el caudal es el cociente entre la variación de volumen y la de tiempo. En el sector de mayor sección la velocidad es menor, y la circulación sanguínea es pulsátil, de modo que solo se aproxima a un régimen estacionario.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q46',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'Para un tubo cilíndrico de paredes rígidas, por el que fluye un líquido newtoniano con régimen laminar, marque la opción correcta:',
    options: [
      'Para una velocidad del líquido mayor a la velocidad crítica, la ley de Poiseuille establece una relación no lineal entre el gasto y la diferencia de presión entre los extremos del tubo.',
      'La resistencia viscosa corresponde a la pendiente del gráfico gasto en función de la diferencia de presión.',
      'La resistencia viscosa es inversamente proporcional a la cuarta potencia del radio del tubo.',
    ],
    correctIndex: 2,
    explanation: 'La resistencia viscosa es inversamente proporcional a la cuarta potencia del radio, lo que hace del calibre el determinante dominante. La ley de Poiseuille solo vale en régimen laminar, y la resistencia es la inversa de la pendiente del gráfico de gasto contra presión.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q47',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Respecto a las leyes y a la difusión de los gases, indique cuál de las opciones considera correcta:',
    options: [
      'Los gases difunden en medio gaseoso de una región de mayor presión parcial hacia otra de menor presión parcial.',
      'El flujo de O2 y CO2 ocurre a favor del gradiente de presión total ejercida por una mezcla de gases.',
      'La velocidad de difusión de los gases es inversamente proporcional a la masa molar.',
    ],
    correctIndex: 0,
    explanation: 'Cada gas difunde según su propio gradiente de presión parcial, y no según la presión total de la mezcla. La velocidad de difusión se relaciona con la raíz cuadrada de la masa molar, no con la masa molar directamente.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q48',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'Con respecto a los volúmenes y capacidades pulmonares, marque la opción correcta:',
    options: [
      'La capacidad inspiratoria es igual a la suma del volumen de reserva inspiratoria, el volumen corriente y el volumen residual.',
      'La capacidad residual funcional es la cantidad de aire que queda en los pulmones luego de una espiración tranquila.',
      'En una espiración forzada el pulmón se colapsa totalmente.',
    ],
    correctIndex: 1,
    explanation: 'La capacidad residual funcional es el aire que permanece en el pulmón tras una espiración tranquila. La capacidad inspiratoria no incluye el volumen residual, y ni siquiera una espiración forzada vacía el pulmón por completo: siempre queda el volumen residual.',
  },
  {
    id: 'CYR-PROTOTIPO-5-Q49',
    source: 'exam',
    exam: 'PROTOTIPO 5',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Con respecto al electrocardiograma (ECG), marque la opción correcta:',
    options: [
      'El vectocardiograma no se puede obtener a partir del ECG.',
      'El intervalo PR es la región del ECG que va desde el fin de la onda P al comienzo de la onda Q.',
      'A partir del registro electrocardiográfico se puede determinar el módulo, la dirección y el sentido del eje eléctrico medio.',
    ],
    correctIndex: 2,
    explanation: 'El trazado electrocardiográfico permite reconstruir el eje eléctrico medio en módulo, dirección y sentido a partir de las derivaciones. El vectocardiograma sí se deriva del ECG, y el tramo que va del fin de la onda P al comienzo del QRS es el segmento PR, no el intervalo.',
  },
  // ============== PROTOTIPO 6 ==============
  {
    id: 'CYR-PROTOTIPO-6-Q26',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'En relación a la presión arterial en condiciones fisiológicas, es correcto afirmar que:',
    options: [
      'Su onda de pulso se amortigua a medida que la sangre avanza hacia la periferia por el sistema arterial.',
      'Su valor máximo durante el ciclo cardíaco en reposo es de 60 mm Hg.',
      'Su valor mínimo durante el ciclo cardíaco en reposo es de 30 mm Hg.',
    ],
    correctIndex: 0,
    explanation: 'La onda de pulso se amortigua a medida que la sangre avanza hacia la periferia, hasta desaparecer en el lecho capilar. Los valores que proponen las otras dos opciones no corresponden a las presiones sistólica y diastólica de reposo.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q27',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'hemodinamia',
    materia: 'cyr',
    question: 'La presión arterial media se calcula como:',
    options: [
      'La presión sistólica más la diastólica dividido dos.',
      'La presión diastólica más un tercio de la presión diferencial.',
      'La diferencia entre la presión sistólica y la presión diastólica.',
    ],
    correctIndex: 1,
    explanation: 'Como la diástole ocupa una fracción mayor del ciclo que la sístole, la presión media se aproxima sumando a la diastólica un tercio de la presión diferencial. El promedio simple sobreestima el valor, y la diferencia entre ambas presiones es la presión diferencial, no la media.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q28',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'intercambio-gaseoso',
    materia: 'cyr',
    question: 'Con respecto a la curva de disociación de la hemoglobina por el oxígeno:',
    options: [
      'Durante el ejercicio físico la curva se desvía hacia la izquierda.',
      'Un incremento del P50 indica una menor afinidad de la hemoglobina por el oxígeno.',
      'Una desviación de la curva hacia la derecha implica un aumento de la afinidad de la hemoglobina por el O2.',
    ],
    correctIndex: 1,
    explanation: 'La P50 es la presión de oxígeno a la que la hemoglobina está saturada al cincuenta por ciento, de modo que si aumenta hace falta más oxígeno para la misma saturación: la afinidad bajó. El desplazamiento a la derecha implica menor afinidad, y el ejercicio desplaza la curva en ese sentido.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q30',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: '¿Cuál de las siguientes condiciones dará como resultado un aumento en el gasto cardíaco?',
    options: [
      'Aumento de la poscarga.',
      'Aumento de la frecuencia cardíaca.',
      'Disminución del volumen de eyección sistólico.',
    ],
    correctIndex: 1,
    explanation: 'El gasto cardíaco es el producto de la frecuencia por el volumen sistólico, así que aumentar la frecuencia lo eleva. Un aumento de la poscarga y una caída del volumen sistólico lo reducen.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q31',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Con respecto a las características de los vasos sanguíneos:',
    options: [
      'En las grandes arterias la velocidad de conducción de la sangre es baja.',
      'En las venas se albergan grandes volúmenes de sangre.',
      'En los capilares la presión sanguínea es alta.',
    ],
    correctIndex: 1,
    explanation: 'El sistema venoso es el reservorio de volumen del aparato circulatorio y aloja la mayor parte de la sangre. En las grandes arterias la velocidad es alta por su sección pequeña, y la presión capilar es baja para permitir el intercambio.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q32',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'Con respecto al flujo coronario e irrigación ventricular:',
    options: [
      'Durante la sístole, las fuerzas compresivas extravasculares disminuyen el flujo en el ventrículo izquierdo.',
      'La perfusión cardíaca se caracteriza por ser constante a lo largo del ciclo cardíaco.',
      'Durante la sístole, la sangre tiende a acumularse a nivel de los vasos intramurales.',
    ],
    correctIndex: 0,
    explanation: 'Durante la sístole el miocardio comprime sus propios vasos y reduce el flujo en el ventrículo izquierdo, de modo que la perfusión no es constante a lo largo del ciclo. Esa compresión expulsa la sangre de los vasos intramurales en lugar de acumularla.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q33',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'El control del flujo sanguíneo local por el endotelio vascular está mediado por la liberación del siguiente vasodilatador:',
    options: [
      'Angiotensina.',
      'Óxido nítrico.',
      'Noradrenalina.',
    ],
    correctIndex: 1,
    explanation: 'El endotelio regula el tono vascular liberando óxido nítrico, que difunde al músculo liso subyacente y lo relaja. La angiotensina y la noradrenalina son vasoconstrictoras y no provienen del endotelio.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q34',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En ausencia de surfactante pulmonar:',
    options: [
      'Desaparece la histéresis pulmonar.',
      'La distensibilidad pulmonar aumenta.',
      'Se evita el colapso de los alveolos de menor radio.',
    ],
    correctIndex: 0,
    explanation: 'La histéresis pulmonar, la diferencia entre las curvas de inspiración y espiración, depende del comportamiento del surfactante y desaparece sin él. Su ausencia reduce la distensibilidad y favorece el colapso de los alvéolos pequeños.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q35',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'A nivel pulmonar, el volumen corriente se define como:',
    options: [
      'El volumen de aire inspirado y espirado durante una respiración forzada.',
      'El volumen de aire inspirado y espirado durante una respiración en reposo.',
      'El volumen de aire que queda en los pulmones después de una espiración forzada.',
    ],
    correctIndex: 1,
    explanation: 'El volumen corriente es el que se moviliza en cada ciclo respiratorio tranquilo. Los volúmenes movilizados en esfuerzo máximo son los de reserva, y el que permanece tras una espiración forzada es el volumen residual.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q36',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'En relación con las estructuras involucradas en la generación del ritmo respiratorio:',
    options: [
      'El grupo respiratorio dorsal tiene neuronas que se activan principalmente durante la espiración.',
      'El ritmo básico de la respiración se genera principalmente por neuronas barorreceptoras del hipotálamo lateral.',
      'Las neuronas del grupo respiratorio ventral se activan preferentemente cuando se requieren niveles elevados de ventilación pulmonar.',
    ],
    correctIndex: 2,
    explanation: 'El grupo respiratorio ventral se recluta cuando aumenta la demanda ventilatoria, ya que la respiración tranquila la sostiene el grupo dorsal. El ritmo básico se genera en el bulbo, no en el hipotálamo, y las neuronas del grupo dorsal son inspiratorias.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q38',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'control-respiracion',
    materia: 'cyr',
    question: 'Sobre los quimiorreceptores ubicados a nivel central, estos responden de forma más efectiva a:',
    options: [
      'Un aumento en la concentración de hidrogeniones.',
      'Una disminución en la PO2 arterial.',
      'Un aumento en la PCO2.',
    ],
    correctIndex: 0,
    explanation: 'Los quimiorreceptores centrales del bulbo detectan los hidrogeniones del líquido cefalorraquídeo. El CO2 actúa sobre ellos de forma indirecta, tras difundir y generar esos hidrogeniones, y la hipoxia es el estímulo de los receptores periféricos.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q39',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Con respecto a la fisiología cardiovascular:',
    options: [
      'El sistema nervioso simpático disminuye la frecuencia cardíaca.',
      'La frecuencia cardíaca está determinada principalmente por la postcarga.',
      'El estado inotrópico del músculo cardíaco está determinado por la disponibilidad de calcio.',
    ],
    correctIndex: 2,
    explanation: 'La fuerza de contracción depende de la cantidad de calcio disponible para los miofilamentos. El simpático acelera la frecuencia en lugar de reducirla, y la frecuencia la fija el nódulo sinusal, no la poscarga.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q40',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: '¿Qué tipo de capilar forma parte de la barrera hematoáerea?',
    options: [
      'Continuo.',
      'Fenestrado.',
      'Sinusoide.',
    ],
    correctIndex: 0,
    explanation: 'La barrera hematoaérea se apoya en un capilar continuo, cuyo endotelio sin fenestras permite un intercambio gaseoso selectivo. Los fenestrados y los sinusoides corresponden a lechos donde se requiere mayor permeabilidad.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q42',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'circulacion-regional',
    materia: 'cyr',
    question: 'La superficie interna del corazón está tapizada por:',
    options: [
      'Cápsula de tejido conjuntivo denso',
      'Músculo cardíaco especializado',
      'Endotelio',
    ],
    correctIndex: 2,
    explanation: 'La superficie interna de las cavidades cardíacas es el endocardio, tapizado por endotelio en continuidad con el de los vasos. El músculo cardíaco especializado forma el sistema de conducción, dentro del miocardio.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q43',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿Cuál de las siguientes son características histológicas de los bronquiolos propiamente dichos?',
    options: [
      'Presentan alveolos en su pared',
      'Carecen de cartílago en su pared.',
      'Están tapizados por un epitelio seudoestratificado cilíndrico con células caliciformes',
    ],
    correctIndex: 1,
    explanation: 'El bronquiolo propiamente dicho ya no tiene cartílago ni células caliciformes, y su epitelio es simple. Los alvéolos en la pared aparecen recién en el bronquiolo respiratorio.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q44',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'histologia-cyr',
    materia: 'cyr',
    question: '¿En qué sector del aparato respiratorio se encuentran células caliciformes formando parte del revestimiento epitelial?',
    options: [
      'En la laringe.',
      'En los bronquiolos.',
      'En los tabiques pulmonares',
    ],
    correctIndex: 0,
    explanation: 'Las células caliciformes acompañan al epitelio respiratorio de las vías aéreas proximales, incluida la laringe. Desaparecen a nivel bronquiolar, donde las reemplazan las células de Clara, y los tabiques alveolares están tapizados por neumocitos.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q45',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'mecanica-ventilatoria',
    materia: 'cyr',
    question: 'En relación con la mecánica pulmonar:',
    options: [
      'Cuando la presión transmural torácica es igual a cero, las presiones transmurales pulmonar y toracopulmonar son iguales y de signo contrario.',
      'La presión transmural pulmonar es siempre positiva para cualquier porcentaje de capacidad vital.',
      'En el 0% de la capacidad vital, la presión transmural pulmonar es igual a cero.',
    ],
    correctIndex: 1,
    explanation: 'El pulmón se mantiene distendido en todo el rango de capacidad vital, de modo que su presión transmural es siempre positiva; si llegara a cero, el pulmón colapsaría. Ni siquiera al final de una espiración máxima esa presión se anula.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q47',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'electrocardiografia',
    materia: 'cyr',
    question: 'Dado un líquido ideal que circula con régimen laminar por un sistema de tubos ubicados en un plano horizontal:',
    options: [
      'Si todos los tubos tienen igual diámetro y están conectados en serie, la velocidad media en todos los sectores del sistema será la misma.',
      'La presión hidrostática en los diferentes tramos será mayor cuanto más rápido circule el líquido.',
      'La velocidad del líquido es independiente de la sección del tubo.',
    ],
    correctIndex: 0,
    explanation: 'Si la sección no cambia y los tubos están en serie, el caudal constante impone la misma velocidad media en todos los tramos. Por Bernoulli, donde el líquido circula más rápido la presión es menor, y la velocidad sí depende de la sección.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q48',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Respecto al principio de Bernoulli:',
    options: [
      'Establece que para un líquido real, la suma de la energía cinética y de presión en un volumen de líquido en un tubo permanece constante.',
      'Establece que para un líquido ideal, la suma de la energía cinética, potencial gravitatoria y de presión en un volumen de líquido en un tubo permanece constante.',
      'Establece que para un líquido no newtoniano, la suma de la energía gravitatoria y de presión en un volumen de líquido en un tubo aumenta al estrecharse el tubo.',
    ],
    correctIndex: 1,
    explanation: 'El principio de Bernoulli se enuncia para un líquido ideal y establece que la suma de la energía cinética, la potencial gravitatoria y la de presión permanece constante a lo largo del recorrido. En un líquido real parte de esa energía se disipa por rozamiento.',
  },
  {
    id: 'CYR-PROTOTIPO-6-Q49',
    source: 'exam',
    exam: 'PROTOTIPO 6',
    topic: 'fisiologia-cardiaca',
    materia: 'cyr',
    question: 'Con respecto al potencial de acción del nódulo sinusal:',
    options: [
      'Presenta una fase de meseta vinculada al balance de dos corrientes.',
      'Presenta una fase de despolarización (fase 0) debida a una corriente de Ca2+.',
      'La fase de despolarización espontánea (fase 4) es debida a una alta densidad de canales de K+.',
    ],
    correctIndex: 1,
    explanation: 'La fase 0 del nódulo sinusal depende de una corriente de calcio, y no de sodio como en el miocardio contráctil, lo que explica su ascenso lento. No presenta meseta, y la despolarización espontánea de la fase 4 se debe a la corriente de entrada If, no a canales de potasio.',
  },
];
